    # See also UnicodeSpecials.py
    fractions = {
        #0x02044: "FRACTION SLASH",

        0x000BC: "VULGAR FRACTION ONE QUARTER",
        0x000BD: "VULGAR FRACTION ONE HALF",
        0x000BE: "VULGAR FRACTION THREE QUARTERS",
        0x02150: "VULGAR FRACTION ONE SEVENTH",
        0x02151: "VULGAR FRACTION ONE NINTH",
        0x02152: "VULGAR FRACTION ONE TENTH",
        0x02153: "VULGAR FRACTION ONE THIRD",
        0x02154: "VULGAR FRACTION TWO THIRDS",
        0x02155: "VULGAR FRACTION ONE FIFTH",
        0x02156: "VULGAR FRACTION TWO FIFTHS",
        0x02157: "VULGAR FRACTION THREE FIFTHS",
        0x02158: "VULGAR FRACTION FOUR FIFTHS",
        0x02159: "VULGAR FRACTION ONE SIXTH",
        0x0215A: "VULGAR FRACTION FIVE SIXTHS",
        0x0215B: "VULGAR FRACTION ONE EIGHTH",
        0x0215C: "VULGAR FRACTION THREE EIGHTHS",
        0x0215D: "VULGAR FRACTION FIVE EIGHTHS",
        0x0215E: "VULGAR FRACTION SEVEN EIGHTHS",
        0x02189: "VULGAR FRACTION ZERO THIRDS",

        0x00B72: "ORIYA FRACTION ONE QUARTER",
        0x00B73: "ORIYA FRACTION ONE HALF",
        0x00B74: "ORIYA FRACTION THREE QUARTERS",
        0x00B75: "ORIYA FRACTION ONE SIXTEENTH",
        0x00B76: "ORIYA FRACTION ONE EIGHTH",
        0x00B77: "ORIYA FRACTION THREE SIXTEENTHS",

        0x00C78: "TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR",
        0x00C79: "TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR",
        0x00C7A: "TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR",
        0x00C7B: "TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR",
        0x00C7C: "TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR",
        0x00C7D: "TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR",
        0x00C7E: "TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR",

        0x00D73: "MALAYALAM FRACTION ONE QUARTER",
        0x00D74: "MALAYALAM FRACTION ONE HALF",
        0x00D75: "MALAYALAM FRACTION THREE QUARTERS",

        0x0215F: "FRACTION NUMERATOR ONE",

        0x02CFD: "COPTIC FRACTION ONE HALF",

        0x0A830: "NORTH INDIC FRACTION ONE QUARTER",
        0x0A831: "NORTH INDIC FRACTION ONE HALF",
        0x0A832: "NORTH INDIC FRACTION THREE QUARTERS",
        0x0A833: "NORTH INDIC FRACTION ONE SIXTEENTH",
        0x0A834: "NORTH INDIC FRACTION ONE EIGHTH",
        0x0A835: "NORTH INDIC FRACTION THREE SIXTEENTHS",

        0x10E7B: "RUMI FRACTION ONE HALF",
        0x10E7C: "RUMI FRACTION ONE QUARTER",
        0x10E7D: "RUMI FRACTION ONE THIRD",
        0x10E7E: "RUMI FRACTION TWO THIRDS",
    }
