#!/usr/bin/env python
#
# UnicodeSpecials.py
#
# 2018-11-08: Written. Copyright by Steven J. DeRose.
# I hereby dedicate my work herein to the Public Domain.
#
# To do:
#
from __future__ import print_function
#import sys, os
import argparse
#import re
#import string
#import math
#import codecs

#from collections import defaultdict

__metadata__ = {
    'title'        : "UnicodeSpecials.py",
    'rightsHolder' : "Steven J. DeRose",
    'creator'      : "http://viaf.org/viaf/50334488",
    'type'         : "http://purl.org/dc/dcmitype/Software",
    'language'     : "Python 3.7",
    'created'      : "2018-11-08",
    'modified'     : "2020-02-28",
    'publisher'    : "http://github.com/sderose",
    'license'      : "https://creativecommons.org/licenses/by-sa/3.0/"
}
__version__ = __metadata__['modified']

descr = """
=Description=

Provide lists of characters in categories that aren't quite the same as
off-the-shelf Unicode categories.

You can request them as dicts keyed on the code point, with array values
that include the name and other relevant info (such as fraction values,
brace sides, space widths, etc.).

You'll also be able to get them as strings or as regexes groups.

Should also have a way to get lists of all the characters in any particular
category. In the meantime use my `ord` for that.

For mathematical Latin and Greek sets, see my `mathUnicode.py`.

=Related Commands=

=Known bugs and Limitations=

=Rights=

Copyright 2018-11-08 by Steven J. DeRose. This work is licensed under a Creative Commons
Attribution-Share Alike 3.0 Unported License. For further information on
this license, see [http://creativecommons.org/licenses/by-sa/3.0].

For the most recent version, see [http://www.derose.net/steve/utilities] or
[http://github.com/sderose].

=Options=
"""


###############################################################################
#
class UnicodeSpecials:
    def __init__(self):
        self.brackets = {
        0x1D11: ( "X", "5	MUSICAL SYMBOL BRACKET" ),
        0x1D15: ( "X", "6	MUSICAL SYMBOL PARENTHESIS NOTEHEAD" ),
        0x2E0A: ( "R", "RIGHT TRANSPOSITION BRACKET" ),
        0x2E0C: ( "L", "LEFT RAISED OMISSION BRACKET" ),
        0x2E0D: ( "R", "RIGHT RAISED OMISSION BRACKET" ),
        0x2E1C: ( "L", "LEFT LOW PARAPHRASE BRACKET" ),
        0x2E1D: ( "R", "RIGHT LOW PARAPHRASE BRACKET" ),
        0x2E02: ( "L", "LEFT SUBSTITUTION BRACKET" ),
        0x2E03: ( "R", "RIGHT SUBSTITUTION BRACKET" ),
        0x2E04: ( "L", "LEFT DOTTED SUBSTITUTION BRACKET" ),
        0x2E05: ( "R", "RIGHT DOTTED SUBSTITUTION BRACKET" ),
        0x2E09: ( "L", "LEFT TRANSPOSITION BRACKET" ),
        0x2E22: ( "L", "TOP LEFT HALF BRACKET" ),
        0x2E23: ( "R", "TOP RIGHT HALF BRACKET" ),
        0x2E24: ( "L", "BOTTOM LEFT HALF BRACKET" ),
        0x2E25: ( "R", "BOTTOM RIGHT HALF BRACKET" ),
        0x2E26: ( "L", "LEFT SIDEWAYS U BRACKET" ),
        0x2E27: ( "R", "RIGHT SIDEWAYS U BRACKET" ),
        0x2E28: ( "L", "LEFT DOUBLE PARENTHESIS" ),
        0x2E29: ( "R", "RIGHT DOUBLE PARENTHESIS" ),
        0x005B: ( "L", "LEFT SQUARE BRACKET" ),
        0x005D: ( "R", "RIGHT SQUARE BRACKET" ),
        0x007B: ( "L", "LEFT CURLY BRACKET" ),
        0x007D: ( "R", "RIGHT CURLY BRACKET" ),
        0x23A0: ( "R", "RIGHT PARENTHESIS LOWER HOOK" ),
        0x23A1: ( "L", "LEFT SQUARE BRACKET UPPER CORNER" ),
        0x23A2: ( "L", "LEFT SQUARE BRACKET EXTENSION" ),
        0x23A3: ( "L", "LEFT SQUARE BRACKET LOWER CORNER" ),
        0x23A4: ( "R", "RIGHT SQUARE BRACKET UPPER CORNER" ),
        0x23A5: ( "R", "RIGHT SQUARE BRACKET EXTENSION" ),
        0x23A6: ( "R", "RIGHT SQUARE BRACKET LOWER CORNER" ),
        0x23A7: ( "L", "LEFT CURLY BRACKET UPPER HOOK" ),
        0x23A8: ( "L", "LEFT CURLY BRACKET MIDDLE PIECE" ),
        0x23A9: ( "L", "LEFT CURLY BRACKET LOWER HOOK" ),
        0x23AA: ( "X", "CURLY BRACKET EXTENSION" ),
        0x23AB: ( "R", "RIGHT CURLY BRACKET UPPER HOOK" ),
        0x23AC: ( "R", "RIGHT CURLY BRACKET MIDDLE PIECE" ),
        0x23AD: ( "R", "RIGHT CURLY BRACKET LOWER HOOK" ),
        0x23B0: ( "?", "UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION" ),
        0x23B1: ( "?", "UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION" ),
        0x23B4: ( "T", "TOP SQUARE BRACKET" ),
        0x23B5: ( "B", "BOTTOM SQUARE BRACKET" ),
        0x23B6: ( "B", "BOTTOM SQUARE BRACKET OVER TOP SQUARE BRACKET" ),
        0x23DC: ( "T", "TOP PARENTHESIS (mathematical use)" ),
        0x23DD: ( "B", "BOTTOM PARENTHESIS (mathematical use)" ),
        0x23DE: ( "T", "TOP CURLY BRACKET (mathematical use)" ),
        0x23DF: ( "B", "BOTTOM CURLY BRACKET (mathematical use)" ),
        0x23E0: ( "T", "TOP TORTOISE SHELL BRACKET (mathematical use)" ),
        0x23E1: ( "B", "BOTTOM TORTOISE SHELL BRACKET (mathematical use)" ),
        0x27E6: ( "L", "MATHEMATICAL LEFT WHITE SQUARE BRACKET" ),
        0x27E7: ( "R", "MATHEMATICAL RIGHT WHITE SQUARE BRACKET" ),
        0x27E8: ( "L", "MATHEMATICAL LEFT ANGLE BRACKET" ),
        0x27E9: ( "R", "MATHEMATICAL RIGHT ANGLE BRACKET" ),
        0x27EA: ( "L", "MATHEMATICAL LEFT DOUBLE ANGLE BRACKET" ),
        0x27EB: ( "R", "MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET" ),
        0x27EC: ( "L", "MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET" ),
        0x27ED: ( "R", "MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET" ),
        0x27EE: ( "L", "MATHEMATICAL LEFT FLATTENED PARENTHESIS" ),
        0x27EF: ( "R", "MATHEMATICAL RIGHT FLATTENED PARENTHESIS" ),
        0x0028: ( "L", "LEFT PARENTHESIS" ),
        0x0029: ( "R", "RIGHT PARENTHESIS" ),
        0x29FC: ( "L", "LEFT-POINTING CURVED ANGLE BRACKET" ),
        0x29FD: ( "R", "RIGHT-POINTING CURVED ANGLE BRACKET" ),
        0x207D: ( "L", "SUPERSCRIPT LEFT PARENTHESIS" ),
        0x207E: ( "R", "SUPERSCRIPT RIGHT PARENTHESIS" ),
        0x208D: ( "L", "SUBSCRIPT LEFT PARENTHESIS" ),
        0x208E: ( "R", "SUBSCRIPT RIGHT PARENTHESIS" ),
        0x232A: ( "R", "RIGHT-POINTING ANGLE BRACKET" ),
        0x239B: ( "L", "LEFT PARENTHESIS UPPER HOOK" ),
        0x239C: ( "L", "LEFT PARENTHESIS EXTENSION" ),
        0x239D: ( "L", "LEFT PARENTHESIS LOWER HOOK" ),
        0x239E: ( "R", "RIGHT PARENTHESIS UPPER HOOK" ),
        0x239F: ( "R", "RIGHT PARENTHESIS EXTENSION" ),
        0x276A: ( "L", "MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT" ),
        0x276B: ( "R", "MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT" ),
        0x276C: ( "L", "MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT" ),
        0x276D: ( "R", "MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT" ),
        0x298A: ( "R", "Z NOTATION RIGHT BINDING BRACKET" ),
        0x298B: ( "L", "LEFT SQUARE BRACKET WITH UNDERBAR" ),
        0x298C: ( "R", "RIGHT SQUARE BRACKET WITH UNDERBAR" ),
        0x298D: ( "L", "LEFT SQUARE BRACKET WITH TICK IN TOP CORNER" ),
        0x298E: ( "R", "RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER" ),
        0x298F: ( "L", "LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER" ),
        0x300A: ( "L", "LEFT DOUBLE ANGLE BRACKET" ),
        0x300B: ( "R", "RIGHT DOUBLE ANGLE BRACKET" ),
        0x300C: ( "L", "LEFT CORNER BRACKET" ),
        0x300D: ( "R", "RIGHT CORNER BRACKET" ),
        0x300E: ( "L", "LEFT WHITE CORNER BRACKET" ),
        0x300F: ( "R", "RIGHT WHITE CORNER BRACKET" ),
        0x301A: ( "L", "LEFT WHITE SQUARE BRACKET" ),
        0x301B: ( "R", "RIGHT WHITE SQUARE BRACKET" ),
        0x2045: ( "L", "LEFT SQUARE BRACKET WITH QUILL" ),
        0x2046: ( "R", "RIGHT SQUARE BRACKET WITH QUILL" ),
        0x2329: ( "L", "LEFT-POINTING ANGLE BRACKET" ),
        0x2768: ( "L", "MEDIUM LEFT PARENTHESIS ORNAMENT" ),
        0x2769: ( "R", "MEDIUM RIGHT PARENTHESIS ORNAMENT" ),
        0x2770: ( "L", "HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT" ),
        0x2771: ( "R", "HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT" ),
        0x2772: ( "L", "LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT" ),
        0x2773: ( "R", "LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT" ),
        0x2774: ( "L", "MEDIUM LEFT CURLY BRACKET ORNAMENT" ),
        0x2775: ( "R", "MEDIUM RIGHT CURLY BRACKET ORNAMENT" ),
        0x2983: ( "L", "LEFT WHITE CURLY BRACKET" ),
        0x2984: ( "R", "RIGHT WHITE CURLY BRACKET" ),
        0x2985: ( "L", "LEFT WHITE PARENTHESIS" ),
        0x2986: ( "R", "RIGHT WHITE PARENTHESIS" ),
        0x2987: ( "L", "Z NOTATION LEFT IMAGE BRACKET" ),
        0x2988: ( "R", "Z NOTATION RIGHT IMAGE BRACKET" ),
        0x2989: ( "L", "Z NOTATION LEFT BINDING BRACKET" ),
        0x2990: ( "R", "RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER" ),
        0x2991: ( "L", "LEFT ANGLE BRACKET WITH DOT" ),
        0x2992: ( "R", "RIGHT ANGLE BRACKET WITH DOT" ),
        0x2993: ( "L", "LEFT ARC LESS-THAN BRACKET" ),
        0x2994: ( "R", "RIGHT ARC GREATER-THAN BRACKET" ),
        0x2995: ( "L", "DOUBLE LEFT ARC GREATER-THAN BRACKET" ),
        0x2996: ( "R", "DOUBLE RIGHT ARC LESS-THAN BRACKET" ),
        0x2997: ( "L", "LEFT BLACK TORTOISE SHELL BRACKET" ),
        0x2998: ( "R", "RIGHT BLACK TORTOISE SHELL BRACKET" ),
        0x3008: ( "L", "LEFT ANGLE BRACKET" ),
        0x3009: ( "R", "RIGHT ANGLE BRACKET" ),
        0x3010: ( "L", "LEFT BLACK LENTICULAR BRACKET" ),
        0x3011: ( "R", "RIGHT BLACK LENTICULAR BRACKET" ),
        0x3014: ( "L", "LEFT TORTOISE SHELL BRACKET" ),
        0x3015: ( "R", "RIGHT TORTOISE SHELL BRACKET" ),
        0x3016: ( "L", "LEFT WHITE LENTICULAR BRACKET" ),
        0x3017: ( "R", "RIGHT WHITE LENTICULAR BRACKET" ),
        0x3018: ( "L", "LEFT WHITE TORTOISE SHELL BRACKET" ),
        0x3019: ( "R", "RIGHT WHITE TORTOISE SHELL BRACKET" ),
        #0xE002: ( "L", "8	TAG LEFT PARENTHESIS" ),
        #0xE002: ( "R", "9	TAG RIGHT PARENTHESIS" ),  # ?????
        #0xE005: ( "L", "B	TAG LEFT SQUARE BRACKET" ),
        #0xE005: ( "R", "D	TAG RIGHT SQUARE BRACKET" ),
        #0xE007: ( "L", "B	TAG LEFT CURLY BRACKET" ),
        #0xE007: ( "R", "D	TAG RIGHT CURLY BRACKET" ),
        0xFD3E: ( "L", "ORNATE LEFT PARENTHESIS" ),
        0xFD3F: ( "R", "ORNATE RIGHT PARENTHESIS" ),
        0xFE3A: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET" ),
        0xFE3B: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET" ),
        0xFE3C: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET" ),
        0xFE3D: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET" ),
        0xFE3E: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET" ),
        0xFE3F: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET" ),
        0xFE5A: ( "R", "SMALL RIGHT PARENTHESIS" ),
        0xFE5B: ( "L", "SMALL LEFT CURLY BRACKET" ),
        0xFE5C: ( "R", "SMALL RIGHT CURLY BRACKET" ),
        0xFE5D: ( "L", "SMALL LEFT TORTOISE SHELL BRACKET" ),
        0xFE5E: ( "R", "SMALL RIGHT TORTOISE SHELL BRACKET" ),
        0xFE17: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET" ),
        0xFE35: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS" ),
        0xFE36: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS" ),
        0xFE37: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET" ),
        0xFE38: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET" ),
        0xFE39: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET" ),
        0xFE40: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET" ),
        0xFE41: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET" ),
        0xFE42: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET" ),
        0xFE43: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET" ),
        0xFE44: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET" ),
        0xFE47: ( "L", "PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET" ),
        0xFE48: ( "R", "PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET" ),
        0xFE59: ( "L", "SMALL LEFT PARENTHESIS" ),
        0xFF3B: ( "L", "FULLWIDTH LEFT SQUARE BRACKET" ),
        0xFF3D: ( "R", "FULLWIDTH RIGHT SQUARE BRACKET" ),
        0xFF5B: ( "L", "FULLWIDTH LEFT CURLY BRACKET" ),
        0xFF5D: ( "R", "FULLWIDTH RIGHT CURLY BRACKET" ),
        0xFF5F: ( "L", "FULLWIDTH LEFT WHITE PARENTHESIS *" ),
        0xFF08: ( "L", "FULLWIDTH LEFT PARENTHESIS" ),
        0xFF09: ( "R", "FULLWIDTH RIGHT PARENTHESIS" ),
        0xFF60: ( "R", "FULLWIDTH RIGHT WHITE PARENTHESIS *" ),
        0xFF62: ( "L", "HALFWIDTH LEFT CORNER BRACKET" ),
        0xFF63: ( "R", "HALFWIDTH RIGHT CORNER BRACKET" ),
        }


        self.currency = {  # Which side does each one go on, and how does Bengali work?
        0x00A3: ( "L", "POUND SIGN" ),
        0x00A4: ( "L", "CURRENCY SIGN" ),
        0x09F4: ( "?", "Bengali currency numerators/denominator" ),
        0x09F5: ( "?", "Bengali currency numerators/denominator" ),
        0x09F6: ( "?", "Bengali currency numerators/denominator" ),
        0x09F7: ( "?", "Bengali currency numerators/denominator" ),
        0x09F8: ( "?", "Bengali currency numerators/denominator" ),
        0x09F9: ( "?", "Bengali currency numerators/denominator" ),
        0x0E3F: ( "?", "THAI BHAT" ),
        0x17DB: ( "?", "KHMER RIEL" ),

        0x20A0: ( "?", "EURO-CURRENCY SIGN" ),
        0x20A1: ( "?", "COLON SIGN" ),
        0x20A2: ( "?", "CRUZEIRO SIGN" ),
        0x20A3: ( "?", "FRENCH FRANC SIGN" ),
        0x20A4: ( "?", "LIRA SIGN" ),
        0x20A5: ( "?", "MILL SIGN" ),
        0x20A6: ( "?", "NAIRA SIGN" ),
        0x20A7: ( "?", "PESETA SIGN" ),
        0x20A8: ( "?", "RUPEE SIGN" ),
        0x20A9: ( "?", "WON SIGN" ),
        0x20AA: ( "?", "NEW SHEQEL SIGN" ),
        0x20AB: ( "?", "DONG SIGN" ),
        0x20AC: ( "?", "EURO SIGN" ),
        0x20AD: ( "?", "KIP SIGN" ),
        0x20AE: ( "?", "TUGRIK SIGN" ),
        0x20AF: ( "?", "DRACHMA SIGN" ),
        0x20B0: ( "?", "GERMAN PENNY SIGN" ),
        0x20B1: ( "?", "PESO SIGN" ),
        0x20B2: ( "?", "GUARANI SIGN" ),
        0x20B3: ( "?", "AUSTRAL SIGN" ),
        0x20B4: ( "?", "HRYVNIA SIGN" ),
        0x20B5: ( "?", "CEDI SIGN" ),
        0x20B6: ( "?", "LIVRE TOURNOIS SIGN" ),
        0x20B7: ( "?", "SPESMILO SIGN" ),
        0x20B8: ( "?", "TENGE SIGN" ),
        0x20B9: ( "?", "INDIAN RUPEE SIGN" ),
        0x20BA: ( "?", "TURKISH LIRA SIGN" ),

        0xFFE1: ( "L", "FULLWIDTH POUND SIGN" ),
        0xFE69: ( "L", "SMALL DOLLAR SIGN" ),
        0xFF04: ( "L", "FULLWIDTH DOLLAR SIGN" ),
        0x1F4B2: ( "L", "HEAVY DOLLAR SIGN" ),
        }

        self.dashes = {
        # code: (mapTO, name)
        0x002D: ( "-",  "HYPHEN-MINUS" ),
        0x00AD: ( "",   "SOFT HYPHEN" ),
        0x058A: ( "-",  "ARMENIAN HYPHEN" ),
        0x1806: ( "",   "MONGOLIAN TODO SOFT HYPHEN" ),
        0x1B60: ( "-",  "BALINESE PAMENENG ( line-breaking hyphen)" ),
        0x2010: ( "-",  "HYPHEN" ),
        0x2011: ( "-",  "NON-BREAKING HYPHEN" ),
        0x2012: ( "-",  "FIGURE DASH" ),
        0x2013: ( "-",  "EN DASH" ),
        0x2014: ( "--", "EM DASH" ),
        0x2027: ( "",   "HYPHENATION POINT" ),
        0x2043: ( "-",  "HYPHEN BULLET" ),
        0x2053: ( "~",  "SWUNG DASH" ),
        0x21E0: ( "<--", "LEFTWARDS DASHED ARROW" ),
        0x21E1: ( None,  "UPWARDS DASHED ARROW" ),
        0x21E2: ( "-->",  "RIGHTWARDS DASHED ARROW" ),
        0x21E3: ( None,  "DOWNWARDS DASHED ARROW" ),
        0x2212: ( "-",  "MINUS" ),
        0x229D: ( "-",  "CIRCLED DASH" ),
        0x2448: ( "-",  "OCR DASH" ),
        0x2504: ( "-",  "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL" ),
        0x2505: ( "-",  "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL" ),
        0x2508: ( "-",  "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL" ),
        0x2509: ( "-",  "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL" ),
        0x254C: ( "-",  "BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL" ),
        0x254D: ( "-",  "BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL" ),
        0x2E17: ( "-",  "DOUBLE OBLIQUE HYPHEN" ),
        0x2E1A: ( "-",  "HYPHEN WITH DIAERESIS" ),
        0x301C: ( "~",  "WAVE DASH" ),
        0x3030: ( "~",  "WAVY DASH" ),
        0x30A0: ( "=",  "KATAKANA-HIRAGANA DOUBLE HYPHEN" ),
        0xFE49: ( "-",  "DASHED OVERLINE" ),
        0xFE4D: ( "_",  "DASHED LOW LINE" ),
        0xFE58: ( "--",  "SMALL EM DASH" ),
        0xFE63: ( "-",  "SMALL HYPHEN-MINUS" ),
        0xFF0D: ( "-",  "FULLWIDTH HYPHEN-MINUS" ),
        }

        self.ULQuotes = { # Punctuation_Initial
        0x00AB: ( "L",  "", "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK *" ),
        0x2018: ( "L",  "", "LEFT SINGLE QUOTATION MARK" ),
        0x201A: ( "L",  "", "SINGLE LOW-9 QUOTATION MARK" ),
        0x201C: ( "L",  "", "LEFT DOUBLE QUOTATION MARK" ),
        0x201E: ( "L",  "", "DOUBLE LOW-9 QUOTATION MARK" ),
        0x2039: ( "L",  "", "SINGLE LEFT-POINTING ANGLE QUOTATION MARK" ),
        0x2E02: ( "L",  "", "LEFT SUBSTITUTION BRACKET" ),
        0x2E04: ( "L",  "", "LEFT DOTTED SUBSTITUTION BRACKET" ),
        0x2E09: ( "L",  "", "LEFT TRANSPOSITION BRACKET" ),
        0x2E0C: ( "L",  "", "LEFT RAISED OMISSION BRACKET" ),
        0x2E1C: ( "L",  "", "LEFT LOW PARAPHRASE BRACKET" ),
        0x2E20: ( "L",  "", "LEFT VERTICAL BAR WITH QUILL" ),
        }


        self.URQuotes = { # Punctuation_Final
        0x00BB: ( "R",  "", "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK *" ),
        0x2019: ( "R",  "", "RIGHT SINGLE QUOTATION MARK" ),
        0x201B: ( "R",  "", "SINGLE HIGH-REVERSED-9 QUOTATION MARK" ),
        0x201D: ( "R",  "", "RIGHT DOUBLE QUOTATION MARK" ),
        0x201F: ( "R",  "", "DOUBLE HIGH-REVERSED-9 QUOTATION MARK" ),
        0x203A: ( "R",  "", "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK" ),
        #0x2358: ( "R",  "", "APL FUNCTIONAL SYMBOL QUOTE UNDERBAR" ),
        #0x235E: ( "R",  "", "APL FUNCTIONAL SYMBOL QUOTE QUAD" ),
        0x2E03: ( "R",  "", "RIGHT SUBSTITUTION BRACKET" ),
        0x2E05: ( "R",  "", "RIGHT DOTTED SUBSTITUTION BRACKET" ),
        0x2E0A: ( "R",  "", "RIGHT TRANSPOSITION BRACKET" ),
        0x2E0D: ( "R",  "", "RIGHT RAISED OMISSION BRACKET" ),
        0x2E1D: ( "R",  "", "RIGHT LOW PARAPHRASE BRACKET" ),
        0x2E21: ( "R",  "", "RIGHT VERTICAL BAR WITH QUILL" ),
        }

        self.UQuotePairs = [
        (0x00AB, 0x00BB, "[LEFT,RIGHT]-POINTING DOUBLE ANGLE QUOTATION MARK *" ),
        (0x2018, 0x2019, "[LEFT,RIGHT] SINGLE QUOTATION MARK" ),
        (0x201A, 0x201B, "SINGLE [LOW-9, HIGH-REVERSED-9] QUOTATION MARK" ),
        (0x201C, 0x201D, "[LEFT,RIGHT] DOUBLE QUOTATION MARK" ),
        (0x201E, 0x201F, "DOUBLE [LOW-9, HIGH-REVERSED-9] QUOTATION MARK" ),
        (0x2039, 0x203A, "SINGLE [LEFT,RIGHT]-POINTING ANGLE QUOTATION MARK" ),
        (0x2E02, 0x2E03, "[LEFT,RIGHT] SUBSTITUTION BRACKET" ),
        (0x2E04, 0x2E05, "[LEFT,RIGHT] DOTTED SUBSTITUTION BRACKET" ),
        (0x2E09, 0x2E0A, "[LEFT,RIGHT] TRANSPOSITION BRACKET" ),
        (0x2E0C, 0x2E0D, "[LEFT,RIGHT] RAISED OMISSION BRACKET" ),
        (0x2E1C, 0x2E1D, "[LEFT,RIGHT] LOW PARAPHRASE BRACKET" ),
        (0x2E20, 0x2E21, "[LEFT,RIGHT] VERTICAL BAR WITH QUILL" ),
        ]


        # Not in the Unicode categories, but perhaps relevant:
        self.UOtherQuotes = {
        0x0060: ( "?",  "", "GRAVE ACCENT" ),

        0x201A: ( "?",  "", "SINGLE LOW-9 QUOTATION MARK" ),
        0x201E: ( "?",  "", "DOUBLE LOW-9 QUOTATION MARK" ),

        0x275B: ( "?",  "", "HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT" ),
        0x275C: ( "?",  "", "HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT" ),
        0x275D: ( "?",  "", "HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT" ),
        0x275E: ( "?",  "", "HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT" ),
        0x276E: ( "?",  "", "HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT" ),
        0x276F: ( "?",  "", "HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT" ),

        0x301D: ( "?",  "", "REVERSED DOUBLE PRIME QUOTATION MARK" ),
        0x301E: ( "?",  "", "DOUBLE PRIME QUOTATION MARK" ),
        0x301F: ( "?",  "", "LOW DOUBLE PRIME QUOTATION MARK" ),


        0x0027: ( "?",  "", "APOSTROPHE" ),
        0x0149: ( "?",  "", "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE" ),
        0x02bc: ( "?",  "", "MODIFIER LETTER APOSTROPHE" ),
        0x02ee: ( "?",  "", "MODIFIER LETTER DOUBLE APOSTROPHE" ),
        0x055a: ( "?",  "", "ARMENIAN APOSTROPHE" ),
        0x07f4: ( "?",  "", "NKO HIGH TONE APOSTROPHE" ),
        0x07f5: ( "?",  "", "NKO LOW TONE APOSTROPHE" ),
        0xff07: ( "?",  "", "FULLWIDTH APOSTROPHE" ),
        }

        self.USpaces = {
        # code: ( size, name )
        0x0009: (  0,  0, "", "CHARACTER TABULATION" ),
        0x000A: (  0,  0, "", "LINE FEED" ),
        0x000B: (  0,  0, "", "LINE TABULATION" ),
        0x000C: (  0,  0, "", "FORM FEED" ),
        0x000D: (  0,  0, "", "CARRIAGE RETURN" ),
        0x0020: (  1,  1, "", "SPACE" ),
        0x0089: (  0,  0, "", "CHARACTER TABULATION WITH JUSTIFICATION" ),
        0x00A0: (  1,  1, "", "NO-BREAK SPACE" ),
        0x1680: (  1,  1, "", "OGHAM SPACE MARK" ),
        0x2000: (  1,  1, "", "EN QUAD" ),
        0x2001: (  2,  1, "", "EM QUAD" ),
        0x2002: (  1,  1, "", "EN SPACE" ),
        0x2003: (  2,  1, "", "EM SPACE" ),
        0x2004: (  1,  3, "", "THREE-PER-EM SPACE" ),
        0x2005: (  1,  4, "", "FOUR-PER-EM SPACE" ),
        0x2006: (  1,  6, "", "SIX-PER-EM SPACE" ),
        0x2007: (  1,  1, "", "FIGURE SPACE" ),
        0x2008: (  1,  1, "", "PUNCTUATION SPACE" ),
        0x2009: (  0,  1, "", "THIN SPACE" ),
        0x200A: (  0,  1, "", "HAIR SPACE" ),
        0x200B: (  0,  1, "", "ZERO WIDTH SPACE" ),
        0x202F: (  0,  1, "", "NARROW NO-BREAK SPACE" ),
        0x205F: (  1,  1, "", "MEDIUM MATHEMATICAL SPACE" ),
        #0x2420: (  1,  1, "", "SYMBOL FOR SPACE" ),
        0x3000: (  1,  1, "", "IDEOGRAPHIC SPACE" ),
        0x303F: (  1,  2, "", "IDEOGRAPHIC HALF FILL SPACE" ),
        }

        self.fractions = {
        # code: ( val, name )
        #0x2044: (  1, 1,  "FRACTION SLASH" ),

        0x00BC: (  1,  4,  "VULGAR FRACTION ONE QUARTER" ),
        0x00BD: (  1,  2,  "VULGAR FRACTION ONE HALF" ),
        0x00BE: (  3,  4,  "VULGAR FRACTION THREE QUARTERS" ),
        0x2150: (  1,  7,  "VULGAR FRACTION ONE SEVENTH" ),
        0x2151: (  1,  9,  "VULGAR FRACTION ONE NINTH" ),
        0x2152: ( 1,  10,  "VULGAR FRACTION ONE TENTH" ),
        0x2153: (  1,  3,  "VULGAR FRACTION ONE THIRD" ),
        0x2154: (  2,  3,  "VULGAR FRACTION TWO THIRDS" ),
        0x2155: (  1,  5,  "VULGAR FRACTION ONE FIFTH" ),
        0x2156: (  2,  5,  "VULGAR FRACTION TWO FIFTHS" ),
        0x2157: (  3,  5,  "VULGAR FRACTION THREE FIFTHS" ),
        0x2158: (  4,  5,  "VULGAR FRACTION FOUR FIFTHS" ),
        0x2159: (  1,  6,  "VULGAR FRACTION ONE SIXTH" ),
        0x215A: (  5,  6,  "VULGAR FRACTION FIVE SIXTHS" ),
        0x215B: (  1,  8,  "VULGAR FRACTION ONE EIGHTH" ),
        0x215C: (  3,  8,  "VULGAR FRACTION THREE EIGHTHS" ),
        0x215D: (  5,  8,  "VULGAR FRACTION FIVE EIGHTHS" ),
        0x215E: (  7,  8,  "VULGAR FRACTION SEVEN EIGHTHS" ),
        0x2189: (  0,  3,  "VULGAR FRACTION ZERO THIRDS" ),

        0x0B72: (  1,  4,  "ORIYA FRACTION ONE QUARTER" ),
        0x0B73: (  1,  2,  "ORIYA FRACTION ONE HALF" ),
        0x0B74: (  3,  4,  "ORIYA FRACTION THREE QUARTERS" ),
        0x0B75: ( 1,  16,  "ORIYA FRACTION ONE SIXTEENTH" ),
        0x0B76: (  1,  8,  "ORIYA FRACTION ONE EIGHTH" ),
        0x0B77: ( 3,  16,  "ORIYA FRACTION THREE SIXTEENTHS" ),

        0x0C78: (  1,  1,  "TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR" ),
        0x0C79: (  1,  1,  "TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR" ),
        0x0C7A: (  1,  1,  "TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR" ),
        0x0C7B: (  1,  1,  "TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR" ),
        0x0C7C: (  1,  1,  "TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR" ),
        0x0C7D: (  1,  1,  "TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR" ),
        0x0C7E: (  1,  1,  "TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR" ),

        0x0D73: (  1,  1,  "MALAYALAM FRACTION ONE QUARTER" ),
        0x0D74: (  1,  1,  "MALAYALAM FRACTION ONE HALF" ),
        0x0D75: (  1,  1,  "MALAYALAM FRACTION THREE QUARTERS" ),

        0x215F: (  1,  1,  "FRACTION NUMERATOR ONE" ),

        0x2CFD: (  1,  1,  "COPTIC FRACTION ONE HALF" ),

        0xA830: (  1,  1,  "NORTH INDIC FRACTION ONE QUARTER" ),
        0xA831: (  1,  1,  "NORTH INDIC FRACTION ONE HALF" ),
        0xA832: (  1,  1,  "NORTH INDIC FRACTION THREE QUARTERS" ),
        0xA833: (  1,  1,  "NORTH INDIC FRACTION ONE SIXTEENTH" ),
        0xA834: (  1,  1,  "NORTH INDIC FRACTION ONE EIGHTH" ),
        0xA835: (  1,  1,  "NORTH INDIC FRACTION THREE SIXTEENTHS" ),

        0x10E7B: (  1,  1,  "RUMI FRACTION ONE HALF" ),
        0x10E7C: (  1,  1,  "RUMI FRACTION ONE QUARTER" ),
        0x10E7D: (  1,  1,  "RUMI FRACTION ONE THIRD" ),
        0x10E7E: (  2,  3,  "RUMI FRACTION TWO THIRDS" ),
        }

        self.ligatures = {
        # Four more, synonymous to ligtures:
            # = latin capital ligature ae (1.0)
            # * in origin a ligature of 017F and 0073
            # = latin small ligature ae (1.0)
            # x (latin small ligature oe - 0153)
            # x (cyrillic small ligature a ie - 04D5)

        0x0132: ( 'IJ',   'LATIN CAPITAL LIGATURE IJ' ),
        0x0133: ( 'ij',   'LATIN SMALL LIGATURE IJ' ),
        0x0152: ( 'OE',   'LATIN CAPITAL LIGATURE OE' ),
        0x0153: ( 'oe',   'LATIN SMALL LIGATURE OE' ),
        0xa7f9: ( 'oe',   'MODIFIER LETTER SMALL LIGATURE OE' ),
        0xfb00: ( 'ff',   'LATIN SMALL LIGATURE FF' ),
        0xfb01: ( 'fi',   'LATIN SMALL LIGATURE FI' ),
        0xfb02: ( 'fl',   'LATIN SMALL LIGATURE FL' ),
        0xfb03: ( 'ffi',  'LATIN SMALL LIGATURE FFI' ),
        0xfb04: ( 'ffl',  'LATIN SMALL LIGATURE FFL' ),
        0xfb05: ( 'st',   'LATIN SMALL LIGATURE LONG S T' ),
        0xfb06: ( 'st',   'LATIN SMALL LIGATURE ST' ),

        0x04a4: ( "", 'CYRILLIC CAPITAL LIGATURE EN GHE' ),
        0x04a5: ( "", 'CYRILLIC SMALL LIGATURE EN GHE' ),
        0x04b4: ( "", 'CYRILLIC CAPITAL LIGATURE TE TSE' ),
        0x04b5: ( "", 'CYRILLIC SMALL LIGATURE TE TSE' ),
        0x04d4: ( "", 'CYRILLIC CAPITAL LIGATURE A IE' ),
        0x04d5: ( "", 'CYRILLIC SMALL LIGATURE A IE' ),

        0x0587: ( "", 'ARMENIAN SMALL LIGATURE ECH YIWN' ),
        0xfb13: ( "", 'ARMENIAN SMALL LIGATURE MEN NOW' ),
        0xfb14: ( "", 'ARMENIAN SMALL LIGATURE MEN ECH' ),
        0xfb15: ( "", 'ARMENIAN SMALL LIGATURE MEN INI' ),
        0xfb16: ( "", 'ARMENIAN SMALL LIGATURE VEW NOW' ),
        0xfb17: ( "", 'ARMENIAN SMALL LIGATURE MEN XEH' ),

        0x05f0: ( "", 'HEBREW LIGATURE YIDDISH DOUBLE VAV' ),
        0x05f1: ( "", 'HEBREW LIGATURE YIDDISH VAV YOD' ),
        0x05f2: ( "", 'HEBREW LIGATURE YIDDISH DOUBLE YOD' ),
        0xfb1f: ( "", 'HEBREW LIGATURE YIDDISH YOD YOD PATAH' ),
        0xfb4f: ( "", 'HEBREW LIGATURE ALEF LAMED' ),

        0x0616: ( "", 'ARABIC SMALL HIGH LIGATURE ALEF WITH LAM WITH YEH' ),
        0x06d6: ( "", 'ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA' ),
        0x06d7: ( "", 'ARABIC SMALL HIGH LIGATURE QAF WITH LAM WITH ALEF MAKSURA' ),
        0xfbea: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF ISOLATED FORM' ),
        0xfbeb: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF FINAL FORM' ),
        0xfbec: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH AE ISOLATED FORM' ),
        0xfbed: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH AE FINAL FORM' ),
        0xfbee: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH WAW ISOLATED FORM' ),
        0xfbef: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH WAW FINAL FORM' ),
        0xfbf0: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH U ISOLATED FORM' ),
        0xfbf1: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH U FINAL FORM' ),
        0xfbf2: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH OE ISOLATED FORM' ),
        0xfbf3: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH OE FINAL FORM' ),
        0xfbf4: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YU ISOLATED FORM' ),
        0xfbf5: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YU FINAL FORM' ),
        0xfbf6: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E ISOLATED FORM' ),
        0xfbf7: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E FINAL FORM' ),
        0xfbf8: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E INITIAL FORM' ),
        0xfbf9: ( "", 'ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfbfa: ( "", 'ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA FINAL FORM' ),
        0xfbfb: ( "", 'ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA INITIAL FORM' ),
        0xfc00: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM ISOLATED FORM' ),
        0xfc01: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HAH ISOLATED FORM' ),
        0xfc02: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM ISOLATED FORM' ),
        0xfc03: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc04: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YEH ISOLATED FORM' ),
        0xfc05: ( "", 'ARABIC LIGATURE BEH WITH JEEM ISOLATED FORM' ),
        0xfc06: ( "", 'ARABIC LIGATURE BEH WITH HAH ISOLATED FORM' ),
        0xfc07: ( "", 'ARABIC LIGATURE BEH WITH KHAH ISOLATED FORM' ),
        0xfc08: ( "", 'ARABIC LIGATURE BEH WITH MEEM ISOLATED FORM' ),
        0xfc09: ( "", 'ARABIC LIGATURE BEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc0a: ( "", 'ARABIC LIGATURE BEH WITH YEH ISOLATED FORM' ),
        0xfc0b: ( "", 'ARABIC LIGATURE TEH WITH JEEM ISOLATED FORM' ),
        0xfc0c: ( "", 'ARABIC LIGATURE TEH WITH HAH ISOLATED FORM' ),
        0xfc0d: ( "", 'ARABIC LIGATURE TEH WITH KHAH ISOLATED FORM' ),
        0xfc0e: ( "", 'ARABIC LIGATURE TEH WITH MEEM ISOLATED FORM' ),
        0xfc0f: ( "", 'ARABIC LIGATURE TEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc10: ( "", 'ARABIC LIGATURE TEH WITH YEH ISOLATED FORM' ),
        0xfc11: ( "", 'ARABIC LIGATURE THEH WITH JEEM ISOLATED FORM' ),
        0xfc12: ( "", 'ARABIC LIGATURE THEH WITH MEEM ISOLATED FORM' ),
        0xfc13: ( "", 'ARABIC LIGATURE THEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc14: ( "", 'ARABIC LIGATURE THEH WITH YEH ISOLATED FORM' ),
        0xfc15: ( "", 'ARABIC LIGATURE JEEM WITH HAH ISOLATED FORM' ),
        0xfc16: ( "", 'ARABIC LIGATURE JEEM WITH MEEM ISOLATED FORM' ),
        0xfc17: ( "", 'ARABIC LIGATURE HAH WITH JEEM ISOLATED FORM' ),
        0xfc18: ( "", 'ARABIC LIGATURE HAH WITH MEEM ISOLATED FORM' ),
        0xfc19: ( "", 'ARABIC LIGATURE KHAH WITH JEEM ISOLATED FORM' ),
        0xfc1a: ( "", 'ARABIC LIGATURE KHAH WITH HAH ISOLATED FORM' ),
        0xfc1b: ( "", 'ARABIC LIGATURE KHAH WITH MEEM ISOLATED FORM' ),
        0xfc1c: ( "", 'ARABIC LIGATURE SEEN WITH JEEM ISOLATED FORM' ),
        0xfc1d: ( "", 'ARABIC LIGATURE SEEN WITH HAH ISOLATED FORM' ),
        0xfc1e: ( "", 'ARABIC LIGATURE SEEN WITH KHAH ISOLATED FORM' ),
        0xfc1f: ( "", 'ARABIC LIGATURE SEEN WITH MEEM ISOLATED FORM' ),
        0xfc20: ( "", 'ARABIC LIGATURE SAD WITH HAH ISOLATED FORM' ),
        0xfc21: ( "", 'ARABIC LIGATURE SAD WITH MEEM ISOLATED FORM' ),
        0xfc22: ( "", 'ARABIC LIGATURE DAD WITH JEEM ISOLATED FORM' ),
        0xfc23: ( "", 'ARABIC LIGATURE DAD WITH HAH ISOLATED FORM' ),
        0xfc24: ( "", 'ARABIC LIGATURE DAD WITH KHAH ISOLATED FORM' ),
        0xfc25: ( "", 'ARABIC LIGATURE DAD WITH MEEM ISOLATED FORM' ),
        0xfc26: ( "", 'ARABIC LIGATURE TAH WITH HAH ISOLATED FORM' ),
        0xfc27: ( "", 'ARABIC LIGATURE TAH WITH MEEM ISOLATED FORM' ),
        0xfc28: ( "", 'ARABIC LIGATURE ZAH WITH MEEM ISOLATED FORM' ),
        0xfc29: ( "", 'ARABIC LIGATURE AIN WITH JEEM ISOLATED FORM' ),
        0xfc2a: ( "", 'ARABIC LIGATURE AIN WITH MEEM ISOLATED FORM' ),
        0xfc2b: ( "", 'ARABIC LIGATURE GHAIN WITH JEEM ISOLATED FORM' ),
        0xfc2c: ( "", 'ARABIC LIGATURE GHAIN WITH MEEM ISOLATED FORM' ),
        0xfc2d: ( "", 'ARABIC LIGATURE FEH WITH JEEM ISOLATED FORM' ),
        0xfc2e: ( "", 'ARABIC LIGATURE FEH WITH HAH ISOLATED FORM' ),
        0xfc2f: ( "", 'ARABIC LIGATURE FEH WITH KHAH ISOLATED FORM' ),
        0xfc30: ( "", 'ARABIC LIGATURE FEH WITH MEEM ISOLATED FORM' ),
        0xfc31: ( "", 'ARABIC LIGATURE FEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc32: ( "", 'ARABIC LIGATURE FEH WITH YEH ISOLATED FORM' ),
        0xfc33: ( "", 'ARABIC LIGATURE QAF WITH HAH ISOLATED FORM' ),
        0xfc34: ( "", 'ARABIC LIGATURE QAF WITH MEEM ISOLATED FORM' ),
        0xfc35: ( "", 'ARABIC LIGATURE QAF WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc36: ( "", 'ARABIC LIGATURE QAF WITH YEH ISOLATED FORM' ),
        0xfc37: ( "", 'ARABIC LIGATURE KAF WITH ALEF ISOLATED FORM' ),
        0xfc38: ( "", 'ARABIC LIGATURE KAF WITH JEEM ISOLATED FORM' ),
        0xfc39: ( "", 'ARABIC LIGATURE KAF WITH HAH ISOLATED FORM' ),
        0xfc3a: ( "", 'ARABIC LIGATURE KAF WITH KHAH ISOLATED FORM' ),
        0xfc3b: ( "", 'ARABIC LIGATURE KAF WITH LAM ISOLATED FORM' ),
        0xfc3c: ( "", 'ARABIC LIGATURE KAF WITH MEEM ISOLATED FORM' ),
        0xfc3d: ( "", 'ARABIC LIGATURE KAF WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc3e: ( "", 'ARABIC LIGATURE KAF WITH YEH ISOLATED FORM' ),
        0xfc3f: ( "", 'ARABIC LIGATURE LAM WITH JEEM ISOLATED FORM' ),
        0xfc40: ( "", 'ARABIC LIGATURE LAM WITH HAH ISOLATED FORM' ),
        0xfc41: ( "", 'ARABIC LIGATURE LAM WITH KHAH ISOLATED FORM' ),
        0xfc42: ( "", 'ARABIC LIGATURE LAM WITH MEEM ISOLATED FORM' ),
        0xfc43: ( "", 'ARABIC LIGATURE LAM WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc44: ( "", 'ARABIC LIGATURE LAM WITH YEH ISOLATED FORM' ),
        0xfc45: ( "", 'ARABIC LIGATURE MEEM WITH JEEM ISOLATED FORM' ),
        0xfc46: ( "", 'ARABIC LIGATURE MEEM WITH HAH ISOLATED FORM' ),
        0xfc47: ( "", 'ARABIC LIGATURE MEEM WITH KHAH ISOLATED FORM' ),
        0xfc48: ( "", 'ARABIC LIGATURE MEEM WITH MEEM ISOLATED FORM' ),
        0xfc49: ( "", 'ARABIC LIGATURE MEEM WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc4a: ( "", 'ARABIC LIGATURE MEEM WITH YEH ISOLATED FORM' ),
        0xfc4b: ( "", 'ARABIC LIGATURE NOON WITH JEEM ISOLATED FORM' ),
        0xfc4c: ( "", 'ARABIC LIGATURE NOON WITH HAH ISOLATED FORM' ),
        0xfc4d: ( "", 'ARABIC LIGATURE NOON WITH KHAH ISOLATED FORM' ),
        0xfc4e: ( "", 'ARABIC LIGATURE NOON WITH MEEM ISOLATED FORM' ),
        0xfc4f: ( "", 'ARABIC LIGATURE NOON WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc50: ( "", 'ARABIC LIGATURE NOON WITH YEH ISOLATED FORM' ),
        0xfc51: ( "", 'ARABIC LIGATURE HEH WITH JEEM ISOLATED FORM' ),
        0xfc52: ( "", 'ARABIC LIGATURE HEH WITH MEEM ISOLATED FORM' ),
        0xfc53: ( "", 'ARABIC LIGATURE HEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc54: ( "", 'ARABIC LIGATURE HEH WITH YEH ISOLATED FORM' ),
        0xfc55: ( "", 'ARABIC LIGATURE YEH WITH JEEM ISOLATED FORM' ),
        0xfc56: ( "", 'ARABIC LIGATURE YEH WITH HAH ISOLATED FORM' ),
        0xfc57: ( "", 'ARABIC LIGATURE YEH WITH KHAH ISOLATED FORM' ),
        0xfc58: ( "", 'ARABIC LIGATURE YEH WITH MEEM ISOLATED FORM' ),
        0xfc59: ( "", 'ARABIC LIGATURE YEH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfc5a: ( "", 'ARABIC LIGATURE YEH WITH YEH ISOLATED FORM' ),
        0xfc5b: ( "", 'ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF ISOLATED FORM' ),
        0xfc5c: ( "", 'ARABIC LIGATURE REH WITH SUPERSCRIPT ALEF ISOLATED FORM' ),
        0xfc5d: ( "", 'ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF ISOLATED FORM' ),
        0xfc5e: ( "", 'ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM' ),
        0xfc5f: ( "", 'ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM' ),
        0xfc60: ( "", 'ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM' ),
        0xfc61: ( "", 'ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM' ),
        0xfc62: ( "", 'ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM' ),
        0xfc63: ( "", 'ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM' ),
        0xfc64: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH REH FINAL FORM' ),
        0xfc65: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ZAIN FINAL FORM' ),
        0xfc66: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM FINAL FORM' ),
        0xfc67: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH NOON FINAL FORM' ),
        0xfc68: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA FINAL FORM' ),
        0xfc69: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YEH FINAL FORM' ),
        0xfc6a: ( "", 'ARABIC LIGATURE BEH WITH REH FINAL FORM' ),
        0xfc6b: ( "", 'ARABIC LIGATURE BEH WITH ZAIN FINAL FORM' ),
        0xfc6c: ( "", 'ARABIC LIGATURE BEH WITH MEEM FINAL FORM' ),
        0xfc6d: ( "", 'ARABIC LIGATURE BEH WITH NOON FINAL FORM' ),
        0xfc6e: ( "", 'ARABIC LIGATURE BEH WITH ALEF MAKSURA FINAL FORM' ),
        0xfc6f: ( "", 'ARABIC LIGATURE BEH WITH YEH FINAL FORM' ),
        0xfc70: ( "", 'ARABIC LIGATURE TEH WITH REH FINAL FORM' ),
        0xfc71: ( "", 'ARABIC LIGATURE TEH WITH ZAIN FINAL FORM' ),
        0xfc72: ( "", 'ARABIC LIGATURE TEH WITH MEEM FINAL FORM' ),
        0xfc73: ( "", 'ARABIC LIGATURE TEH WITH NOON FINAL FORM' ),
        0xfc74: ( "", 'ARABIC LIGATURE TEH WITH ALEF MAKSURA FINAL FORM' ),
        0xfc75: ( "", 'ARABIC LIGATURE TEH WITH YEH FINAL FORM' ),
        0xfc76: ( "", 'ARABIC LIGATURE THEH WITH REH FINAL FORM' ),
        0xfc77: ( "", 'ARABIC LIGATURE THEH WITH ZAIN FINAL FORM' ),
        0xfc78: ( "", 'ARABIC LIGATURE THEH WITH MEEM FINAL FORM' ),
        0xfc79: ( "", 'ARABIC LIGATURE THEH WITH NOON FINAL FORM' ),
        0xfc7a: ( "", 'ARABIC LIGATURE THEH WITH ALEF MAKSURA FINAL FORM' ),
        0xfc7b: ( "", 'ARABIC LIGATURE THEH WITH YEH FINAL FORM' ),
        0xfc7c: ( "", 'ARABIC LIGATURE FEH WITH ALEF MAKSURA FINAL FORM' ),
        0xfc7d: ( "", 'ARABIC LIGATURE FEH WITH YEH FINAL FORM' ),
        0xfc7e: ( "", 'ARABIC LIGATURE QAF WITH ALEF MAKSURA FINAL FORM' ),
        0xfc7f: ( "", 'ARABIC LIGATURE QAF WITH YEH FINAL FORM' ),
        0xfc80: ( "", 'ARABIC LIGATURE KAF WITH ALEF FINAL FORM' ),
        0xfc81: ( "", 'ARABIC LIGATURE KAF WITH LAM FINAL FORM' ),
        0xfc82: ( "", 'ARABIC LIGATURE KAF WITH MEEM FINAL FORM' ),
        0xfc83: ( "", 'ARABIC LIGATURE KAF WITH ALEF MAKSURA FINAL FORM' ),
        0xfc84: ( "", 'ARABIC LIGATURE KAF WITH YEH FINAL FORM' ),
        0xfc85: ( "", 'ARABIC LIGATURE LAM WITH MEEM FINAL FORM' ),
        0xfc86: ( "", 'ARABIC LIGATURE LAM WITH ALEF MAKSURA FINAL FORM' ),
        0xfc87: ( "", 'ARABIC LIGATURE LAM WITH YEH FINAL FORM' ),
        0xfc88: ( "", 'ARABIC LIGATURE MEEM WITH ALEF FINAL FORM' ),
        0xfc89: ( "", 'ARABIC LIGATURE MEEM WITH MEEM FINAL FORM' ),
        0xfc8a: ( "", 'ARABIC LIGATURE NOON WITH REH FINAL FORM' ),
        0xfc8b: ( "", 'ARABIC LIGATURE NOON WITH ZAIN FINAL FORM' ),
        0xfc8c: ( "", 'ARABIC LIGATURE NOON WITH MEEM FINAL FORM' ),
        0xfc8d: ( "", 'ARABIC LIGATURE NOON WITH NOON FINAL FORM' ),
        0xfc8e: ( "", 'ARABIC LIGATURE NOON WITH ALEF MAKSURA FINAL FORM' ),
        0xfc8f: ( "", 'ARABIC LIGATURE NOON WITH YEH FINAL FORM' ),
        0xfc90: ( "", 'ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF FINAL FORM' ),
        0xfc91: ( "", 'ARABIC LIGATURE YEH WITH REH FINAL FORM' ),
        0xfc92: ( "", 'ARABIC LIGATURE YEH WITH ZAIN FINAL FORM' ),
        0xfc93: ( "", 'ARABIC LIGATURE YEH WITH MEEM FINAL FORM' ),
        0xfc94: ( "", 'ARABIC LIGATURE YEH WITH NOON FINAL FORM' ),
        0xfc95: ( "", 'ARABIC LIGATURE YEH WITH ALEF MAKSURA FINAL FORM' ),
        0xfc96: ( "", 'ARABIC LIGATURE YEH WITH YEH FINAL FORM' ),
        0xfc97: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM INITIAL FORM' ),
        0xfc98: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HAH INITIAL FORM' ),
        0xfc99: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH KHAH INITIAL FORM' ),
        0xfc9a: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM INITIAL FORM' ),
        0xfc9b: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HEH INITIAL FORM' ),
        0xfc9c: ( "", 'ARABIC LIGATURE BEH WITH JEEM INITIAL FORM' ),
        0xfc9d: ( "", 'ARABIC LIGATURE BEH WITH HAH INITIAL FORM' ),
        0xfc9e: ( "", 'ARABIC LIGATURE BEH WITH KHAH INITIAL FORM' ),
        0xfc9f: ( "", 'ARABIC LIGATURE BEH WITH MEEM INITIAL FORM' ),
        0xfca0: ( "", 'ARABIC LIGATURE BEH WITH HEH INITIAL FORM' ),
        0xfca1: ( "", 'ARABIC LIGATURE TEH WITH JEEM INITIAL FORM' ),
        0xfca2: ( "", 'ARABIC LIGATURE TEH WITH HAH INITIAL FORM' ),
        0xfca3: ( "", 'ARABIC LIGATURE TEH WITH KHAH INITIAL FORM' ),
        0xfca4: ( "", 'ARABIC LIGATURE TEH WITH MEEM INITIAL FORM' ),
        0xfca5: ( "", 'ARABIC LIGATURE TEH WITH HEH INITIAL FORM' ),
        0xfca6: ( "", 'ARABIC LIGATURE THEH WITH MEEM INITIAL FORM' ),
        0xfca7: ( "", 'ARABIC LIGATURE JEEM WITH HAH INITIAL FORM' ),
        0xfca8: ( "", 'ARABIC LIGATURE JEEM WITH MEEM INITIAL FORM' ),
        0xfca9: ( "", 'ARABIC LIGATURE HAH WITH JEEM INITIAL FORM' ),
        0xfcaa: ( "", 'ARABIC LIGATURE HAH WITH MEEM INITIAL FORM' ),
        0xfcab: ( "", 'ARABIC LIGATURE KHAH WITH JEEM INITIAL FORM' ),
        0xfcac: ( "", 'ARABIC LIGATURE KHAH WITH MEEM INITIAL FORM' ),
        0xfcad: ( "", 'ARABIC LIGATURE SEEN WITH JEEM INITIAL FORM' ),
        0xfcae: ( "", 'ARABIC LIGATURE SEEN WITH HAH INITIAL FORM' ),
        0xfcaf: ( "", 'ARABIC LIGATURE SEEN WITH KHAH INITIAL FORM' ),
        0xfcb0: ( "", 'ARABIC LIGATURE SEEN WITH MEEM INITIAL FORM' ),
        0xfcb1: ( "", 'ARABIC LIGATURE SAD WITH HAH INITIAL FORM' ),
        0xfcb2: ( "", 'ARABIC LIGATURE SAD WITH KHAH INITIAL FORM' ),
        0xfcb3: ( "", 'ARABIC LIGATURE SAD WITH MEEM INITIAL FORM' ),
        0xfcb4: ( "", 'ARABIC LIGATURE DAD WITH JEEM INITIAL FORM' ),
        0xfcb5: ( "", 'ARABIC LIGATURE DAD WITH HAH INITIAL FORM' ),
        0xfcb6: ( "", 'ARABIC LIGATURE DAD WITH KHAH INITIAL FORM' ),
        0xfcb7: ( "", 'ARABIC LIGATURE DAD WITH MEEM INITIAL FORM' ),
        0xfcb8: ( "", 'ARABIC LIGATURE TAH WITH HAH INITIAL FORM' ),
        0xfcb9: ( "", 'ARABIC LIGATURE ZAH WITH MEEM INITIAL FORM' ),
        0xfcba: ( "", 'ARABIC LIGATURE AIN WITH JEEM INITIAL FORM' ),
        0xfcbb: ( "", 'ARABIC LIGATURE AIN WITH MEEM INITIAL FORM' ),
        0xfcbc: ( "", 'ARABIC LIGATURE GHAIN WITH JEEM INITIAL FORM' ),
        0xfcbd: ( "", 'ARABIC LIGATURE GHAIN WITH MEEM INITIAL FORM' ),
        0xfcbe: ( "", 'ARABIC LIGATURE FEH WITH JEEM INITIAL FORM' ),
        0xfcbf: ( "", 'ARABIC LIGATURE FEH WITH HAH INITIAL FORM' ),
        0xfcc0: ( "", 'ARABIC LIGATURE FEH WITH KHAH INITIAL FORM' ),
        0xfcc1: ( "", 'ARABIC LIGATURE FEH WITH MEEM INITIAL FORM' ),
        0xfcc2: ( "", 'ARABIC LIGATURE QAF WITH HAH INITIAL FORM' ),
        0xfcc3: ( "", 'ARABIC LIGATURE QAF WITH MEEM INITIAL FORM' ),
        0xfcc4: ( "", 'ARABIC LIGATURE KAF WITH JEEM INITIAL FORM' ),
        0xfcc5: ( "", 'ARABIC LIGATURE KAF WITH HAH INITIAL FORM' ),
        0xfcc6: ( "", 'ARABIC LIGATURE KAF WITH KHAH INITIAL FORM' ),
        0xfcc7: ( "", 'ARABIC LIGATURE KAF WITH LAM INITIAL FORM' ),
        0xfcc8: ( "", 'ARABIC LIGATURE KAF WITH MEEM INITIAL FORM' ),
        0xfcc9: ( "", 'ARABIC LIGATURE LAM WITH JEEM INITIAL FORM' ),
        0xfcca: ( "", 'ARABIC LIGATURE LAM WITH HAH INITIAL FORM' ),
        0xfccb: ( "", 'ARABIC LIGATURE LAM WITH KHAH INITIAL FORM' ),
        0xfccc: ( "", 'ARABIC LIGATURE LAM WITH MEEM INITIAL FORM' ),
        0xfccd: ( "", 'ARABIC LIGATURE LAM WITH HEH INITIAL FORM' ),
        0xfcce: ( "", 'ARABIC LIGATURE MEEM WITH JEEM INITIAL FORM' ),
        0xfccf: ( "", 'ARABIC LIGATURE MEEM WITH HAH INITIAL FORM' ),
        0xfcd0: ( "", 'ARABIC LIGATURE MEEM WITH KHAH INITIAL FORM' ),
        0xfcd1: ( "", 'ARABIC LIGATURE MEEM WITH MEEM INITIAL FORM' ),
        0xfcd2: ( "", 'ARABIC LIGATURE NOON WITH JEEM INITIAL FORM' ),
        0xfcd3: ( "", 'ARABIC LIGATURE NOON WITH HAH INITIAL FORM' ),
        0xfcd4: ( "", 'ARABIC LIGATURE NOON WITH KHAH INITIAL FORM' ),
        0xfcd5: ( "", 'ARABIC LIGATURE NOON WITH MEEM INITIAL FORM' ),
        0xfcd6: ( "", 'ARABIC LIGATURE NOON WITH HEH INITIAL FORM' ),
        0xfcd7: ( "", 'ARABIC LIGATURE HEH WITH JEEM INITIAL FORM' ),
        0xfcd8: ( "", 'ARABIC LIGATURE HEH WITH MEEM INITIAL FORM' ),
        0xfcd9: ( "", 'ARABIC LIGATURE HEH WITH SUPERSCRIPT ALEF INITIAL FORM' ),
        0xfcda: ( "", 'ARABIC LIGATURE YEH WITH JEEM INITIAL FORM' ),
        0xfcdb: ( "", 'ARABIC LIGATURE YEH WITH HAH INITIAL FORM' ),
        0xfcdc: ( "", 'ARABIC LIGATURE YEH WITH KHAH INITIAL FORM' ),
        0xfcdd: ( "", 'ARABIC LIGATURE YEH WITH MEEM INITIAL FORM' ),
        0xfcde: ( "", 'ARABIC LIGATURE YEH WITH HEH INITIAL FORM' ),
        0xfcdf: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM MEDIAL FORM' ),
        0xfce0: ( "", 'ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HEH MEDIAL FORM' ),
        0xfce1: ( "", 'ARABIC LIGATURE BEH WITH MEEM MEDIAL FORM' ),
        0xfce2: ( "", 'ARABIC LIGATURE BEH WITH HEH MEDIAL FORM' ),
        0xfce3: ( "", 'ARABIC LIGATURE TEH WITH MEEM MEDIAL FORM' ),
        0xfce4: ( "", 'ARABIC LIGATURE TEH WITH HEH MEDIAL FORM' ),
        0xfce5: ( "", 'ARABIC LIGATURE THEH WITH MEEM MEDIAL FORM' ),
        0xfce6: ( "", 'ARABIC LIGATURE THEH WITH HEH MEDIAL FORM' ),
        0xfce7: ( "", 'ARABIC LIGATURE SEEN WITH MEEM MEDIAL FORM' ),
        0xfce8: ( "", 'ARABIC LIGATURE SEEN WITH HEH MEDIAL FORM' ),
        0xfce9: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM MEDIAL FORM' ),
        0xfcea: ( "", 'ARABIC LIGATURE SHEEN WITH HEH MEDIAL FORM' ),
        0xfceb: ( "", 'ARABIC LIGATURE KAF WITH LAM MEDIAL FORM' ),
        0xfcec: ( "", 'ARABIC LIGATURE KAF WITH MEEM MEDIAL FORM' ),
        0xfced: ( "", 'ARABIC LIGATURE LAM WITH MEEM MEDIAL FORM' ),
        0xfcee: ( "", 'ARABIC LIGATURE NOON WITH MEEM MEDIAL FORM' ),
        0xfcef: ( "", 'ARABIC LIGATURE NOON WITH HEH MEDIAL FORM' ),
        0xfcf0: ( "", 'ARABIC LIGATURE YEH WITH MEEM MEDIAL FORM' ),
        0xfcf1: ( "", 'ARABIC LIGATURE YEH WITH HEH MEDIAL FORM' ),
        0xfcf2: ( "", 'ARABIC LIGATURE SHADDA WITH FATHA MEDIAL FORM' ),
        0xfcf3: ( "", 'ARABIC LIGATURE SHADDA WITH DAMMA MEDIAL FORM' ),
        0xfcf4: ( "", 'ARABIC LIGATURE SHADDA WITH KASRA MEDIAL FORM' ),
        0xfcf5: ( "", 'ARABIC LIGATURE TAH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfcf6: ( "", 'ARABIC LIGATURE TAH WITH YEH ISOLATED FORM' ),
        0xfcf7: ( "", 'ARABIC LIGATURE AIN WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfcf8: ( "", 'ARABIC LIGATURE AIN WITH YEH ISOLATED FORM' ),
        0xfcf9: ( "", 'ARABIC LIGATURE GHAIN WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfcfa: ( "", 'ARABIC LIGATURE GHAIN WITH YEH ISOLATED FORM' ),
        0xfcfb: ( "", 'ARABIC LIGATURE SEEN WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfcfc: ( "", 'ARABIC LIGATURE SEEN WITH YEH ISOLATED FORM' ),
        0xfcfd: ( "", 'ARABIC LIGATURE SHEEN WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfcfe: ( "", 'ARABIC LIGATURE SHEEN WITH YEH ISOLATED FORM' ),
        0xfcff: ( "", 'ARABIC LIGATURE HAH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfd00: ( "", 'ARABIC LIGATURE HAH WITH YEH ISOLATED FORM' ),
        0xfd01: ( "", 'ARABIC LIGATURE JEEM WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfd02: ( "", 'ARABIC LIGATURE JEEM WITH YEH ISOLATED FORM' ),
        0xfd03: ( "", 'ARABIC LIGATURE KHAH WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfd04: ( "", 'ARABIC LIGATURE KHAH WITH YEH ISOLATED FORM' ),
        0xfd05: ( "", 'ARABIC LIGATURE SAD WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfd06: ( "", 'ARABIC LIGATURE SAD WITH YEH ISOLATED FORM' ),
        0xfd07: ( "", 'ARABIC LIGATURE DAD WITH ALEF MAKSURA ISOLATED FORM' ),
        0xfd08: ( "", 'ARABIC LIGATURE DAD WITH YEH ISOLATED FORM' ),
        0xfd09: ( "", 'ARABIC LIGATURE SHEEN WITH JEEM ISOLATED FORM' ),
        0xfd0a: ( "", 'ARABIC LIGATURE SHEEN WITH HAH ISOLATED FORM' ),
        0xfd0b: ( "", 'ARABIC LIGATURE SHEEN WITH KHAH ISOLATED FORM' ),
        0xfd0c: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM ISOLATED FORM' ),
        0xfd0d: ( "", 'ARABIC LIGATURE SHEEN WITH REH ISOLATED FORM' ),
        0xfd0e: ( "", 'ARABIC LIGATURE SEEN WITH REH ISOLATED FORM' ),
        0xfd0f: ( "", 'ARABIC LIGATURE SAD WITH REH ISOLATED FORM' ),
        0xfd10: ( "", 'ARABIC LIGATURE DAD WITH REH ISOLATED FORM' ),
        0xfd11: ( "", 'ARABIC LIGATURE TAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd12: ( "", 'ARABIC LIGATURE TAH WITH YEH FINAL FORM' ),
        0xfd13: ( "", 'ARABIC LIGATURE AIN WITH ALEF MAKSURA FINAL FORM' ),
        0xfd14: ( "", 'ARABIC LIGATURE AIN WITH YEH FINAL FORM' ),
        0xfd15: ( "", 'ARABIC LIGATURE GHAIN WITH ALEF MAKSURA FINAL FORM' ),
        0xfd16: ( "", 'ARABIC LIGATURE GHAIN WITH YEH FINAL FORM' ),
        0xfd17: ( "", 'ARABIC LIGATURE SEEN WITH ALEF MAKSURA FINAL FORM' ),
        0xfd18: ( "", 'ARABIC LIGATURE SEEN WITH YEH FINAL FORM' ),
        0xfd19: ( "", 'ARABIC LIGATURE SHEEN WITH ALEF MAKSURA FINAL FORM' ),
        0xfd1a: ( "", 'ARABIC LIGATURE SHEEN WITH YEH FINAL FORM' ),
        0xfd1b: ( "", 'ARABIC LIGATURE HAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd1c: ( "", 'ARABIC LIGATURE HAH WITH YEH FINAL FORM' ),
        0xfd1d: ( "", 'ARABIC LIGATURE JEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd1e: ( "", 'ARABIC LIGATURE JEEM WITH YEH FINAL FORM' ),
        0xfd1f: ( "", 'ARABIC LIGATURE KHAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd20: ( "", 'ARABIC LIGATURE KHAH WITH YEH FINAL FORM' ),
        0xfd21: ( "", 'ARABIC LIGATURE SAD WITH ALEF MAKSURA FINAL FORM' ),
        0xfd22: ( "", 'ARABIC LIGATURE SAD WITH YEH FINAL FORM' ),
        0xfd23: ( "", 'ARABIC LIGATURE DAD WITH ALEF MAKSURA FINAL FORM' ),
        0xfd24: ( "", 'ARABIC LIGATURE DAD WITH YEH FINAL FORM' ),
        0xfd25: ( "", 'ARABIC LIGATURE SHEEN WITH JEEM FINAL FORM' ),
        0xfd26: ( "", 'ARABIC LIGATURE SHEEN WITH HAH FINAL FORM' ),
        0xfd27: ( "", 'ARABIC LIGATURE SHEEN WITH KHAH FINAL FORM' ),
        0xfd28: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM FINAL FORM' ),
        0xfd29: ( "", 'ARABIC LIGATURE SHEEN WITH REH FINAL FORM' ),
        0xfd2a: ( "", 'ARABIC LIGATURE SEEN WITH REH FINAL FORM' ),
        0xfd2b: ( "", 'ARABIC LIGATURE SAD WITH REH FINAL FORM' ),
        0xfd2c: ( "", 'ARABIC LIGATURE DAD WITH REH FINAL FORM' ),
        0xfd2d: ( "", 'ARABIC LIGATURE SHEEN WITH JEEM INITIAL FORM' ),
        0xfd2e: ( "", 'ARABIC LIGATURE SHEEN WITH HAH INITIAL FORM' ),
        0xfd2f: ( "", 'ARABIC LIGATURE SHEEN WITH KHAH INITIAL FORM' ),
        0xfd30: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM INITIAL FORM' ),
        0xfd31: ( "", 'ARABIC LIGATURE SEEN WITH HEH INITIAL FORM' ),
        0xfd32: ( "", 'ARABIC LIGATURE SHEEN WITH HEH INITIAL FORM' ),
        0xfd33: ( "", 'ARABIC LIGATURE TAH WITH MEEM INITIAL FORM' ),
        0xfd34: ( "", 'ARABIC LIGATURE SEEN WITH JEEM MEDIAL FORM' ),
        0xfd35: ( "", 'ARABIC LIGATURE SEEN WITH HAH MEDIAL FORM' ),
        0xfd36: ( "", 'ARABIC LIGATURE SEEN WITH KHAH MEDIAL FORM' ),
        0xfd37: ( "", 'ARABIC LIGATURE SHEEN WITH JEEM MEDIAL FORM' ),
        0xfd38: ( "", 'ARABIC LIGATURE SHEEN WITH HAH MEDIAL FORM' ),
        0xfd39: ( "", 'ARABIC LIGATURE SHEEN WITH KHAH MEDIAL FORM' ),
        0xfd3a: ( "", 'ARABIC LIGATURE TAH WITH MEEM MEDIAL FORM' ),
        0xfd3b: ( "", 'ARABIC LIGATURE ZAH WITH MEEM MEDIAL FORM' ),
        0xfd3c: ( "", 'ARABIC LIGATURE ALEF WITH FATHATAN FINAL FORM' ),
        0xfd3d: ( "", 'ARABIC LIGATURE ALEF WITH FATHATAN ISOLATED FORM' ),
        0xfd50: ( "", 'ARABIC LIGATURE TEH WITH JEEM WITH MEEM INITIAL FORM' ),
        0xfd51: ( "", 'ARABIC LIGATURE TEH WITH HAH WITH JEEM FINAL FORM' ),
        0xfd52: ( "", 'ARABIC LIGATURE TEH WITH HAH WITH JEEM INITIAL FORM' ),
        0xfd53: ( "", 'ARABIC LIGATURE TEH WITH HAH WITH MEEM INITIAL FORM' ),
        0xfd54: ( "", 'ARABIC LIGATURE TEH WITH KHAH WITH MEEM INITIAL FORM' ),
        0xfd55: ( "", 'ARABIC LIGATURE TEH WITH MEEM WITH JEEM INITIAL FORM' ),
        0xfd56: ( "", 'ARABIC LIGATURE TEH WITH MEEM WITH HAH INITIAL FORM' ),
        0xfd57: ( "", 'ARABIC LIGATURE TEH WITH MEEM WITH KHAH INITIAL FORM' ),
        0xfd58: ( "", 'ARABIC LIGATURE JEEM WITH MEEM WITH HAH FINAL FORM' ),
        0xfd59: ( "", 'ARABIC LIGATURE JEEM WITH MEEM WITH HAH INITIAL FORM' ),
        0xfd5a: ( "", 'ARABIC LIGATURE HAH WITH MEEM WITH YEH FINAL FORM' ),
        0xfd5b: ( "", 'ARABIC LIGATURE HAH WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd5c: ( "", 'ARABIC LIGATURE SEEN WITH HAH WITH JEEM INITIAL FORM' ),
        0xfd5d: ( "", 'ARABIC LIGATURE SEEN WITH JEEM WITH HAH INITIAL FORM' ),
        0xfd5e: ( "", 'ARABIC LIGATURE SEEN WITH JEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd5f: ( "", 'ARABIC LIGATURE SEEN WITH MEEM WITH HAH FINAL FORM' ),
        0xfd60: ( "", 'ARABIC LIGATURE SEEN WITH MEEM WITH HAH INITIAL FORM' ),
        0xfd61: ( "", 'ARABIC LIGATURE SEEN WITH MEEM WITH JEEM INITIAL FORM' ),
        0xfd62: ( "", 'ARABIC LIGATURE SEEN WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd63: ( "", 'ARABIC LIGATURE SEEN WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd64: ( "", 'ARABIC LIGATURE SAD WITH HAH WITH HAH FINAL FORM' ),
        0xfd65: ( "", 'ARABIC LIGATURE SAD WITH HAH WITH HAH INITIAL FORM' ),
        0xfd66: ( "", 'ARABIC LIGATURE SAD WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd67: ( "", 'ARABIC LIGATURE SHEEN WITH HAH WITH MEEM FINAL FORM' ),
        0xfd68: ( "", 'ARABIC LIGATURE SHEEN WITH HAH WITH MEEM INITIAL FORM' ),
        0xfd69: ( "", 'ARABIC LIGATURE SHEEN WITH JEEM WITH YEH FINAL FORM' ),
        0xfd6a: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM WITH KHAH FINAL FORM' ),
        0xfd6b: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM WITH KHAH INITIAL FORM' ),
        0xfd6c: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd6d: ( "", 'ARABIC LIGATURE SHEEN WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd6e: ( "", 'ARABIC LIGATURE DAD WITH HAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd6f: ( "", 'ARABIC LIGATURE DAD WITH KHAH WITH MEEM FINAL FORM' ),
        0xfd70: ( "", 'ARABIC LIGATURE DAD WITH KHAH WITH MEEM INITIAL FORM' ),
        0xfd71: ( "", 'ARABIC LIGATURE TAH WITH MEEM WITH HAH FINAL FORM' ),
        0xfd72: ( "", 'ARABIC LIGATURE TAH WITH MEEM WITH HAH INITIAL FORM' ),
        0xfd73: ( "", 'ARABIC LIGATURE TAH WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd74: ( "", 'ARABIC LIGATURE TAH WITH MEEM WITH YEH FINAL FORM' ),
        0xfd75: ( "", 'ARABIC LIGATURE AIN WITH JEEM WITH MEEM FINAL FORM' ),
        0xfd76: ( "", 'ARABIC LIGATURE AIN WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd77: ( "", 'ARABIC LIGATURE AIN WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd78: ( "", 'ARABIC LIGATURE AIN WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd79: ( "", 'ARABIC LIGATURE GHAIN WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd7a: ( "", 'ARABIC LIGATURE GHAIN WITH MEEM WITH YEH FINAL FORM' ),
        0xfd7b: ( "", 'ARABIC LIGATURE GHAIN WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd7c: ( "", 'ARABIC LIGATURE FEH WITH KHAH WITH MEEM FINAL FORM' ),
        0xfd7d: ( "", 'ARABIC LIGATURE FEH WITH KHAH WITH MEEM INITIAL FORM' ),
        0xfd7e: ( "", 'ARABIC LIGATURE QAF WITH MEEM WITH HAH FINAL FORM' ),
        0xfd7f: ( "", 'ARABIC LIGATURE QAF WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd80: ( "", 'ARABIC LIGATURE LAM WITH HAH WITH MEEM FINAL FORM' ),
        0xfd81: ( "", 'ARABIC LIGATURE LAM WITH HAH WITH YEH FINAL FORM' ),
        0xfd82: ( "", 'ARABIC LIGATURE LAM WITH HAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd83: ( "", 'ARABIC LIGATURE LAM WITH JEEM WITH JEEM INITIAL FORM' ),
        0xfd84: ( "", 'ARABIC LIGATURE LAM WITH JEEM WITH JEEM FINAL FORM' ),
        0xfd85: ( "", 'ARABIC LIGATURE LAM WITH KHAH WITH MEEM FINAL FORM' ),
        0xfd86: ( "", 'ARABIC LIGATURE LAM WITH KHAH WITH MEEM INITIAL FORM' ),
        0xfd87: ( "", 'ARABIC LIGATURE LAM WITH MEEM WITH HAH FINAL FORM' ),
        0xfd88: ( "", 'ARABIC LIGATURE LAM WITH MEEM WITH HAH INITIAL FORM' ),
        0xfd89: ( "", 'ARABIC LIGATURE MEEM WITH HAH WITH JEEM INITIAL FORM' ),
        0xfd8a: ( "", 'ARABIC LIGATURE MEEM WITH HAH WITH MEEM INITIAL FORM' ),
        0xfd8b: ( "", 'ARABIC LIGATURE MEEM WITH HAH WITH YEH FINAL FORM' ),
        0xfd8c: ( "", 'ARABIC LIGATURE MEEM WITH JEEM WITH HAH INITIAL FORM' ),
        0xfd8d: ( "", 'ARABIC LIGATURE MEEM WITH JEEM WITH MEEM INITIAL FORM' ),
        0xfd8e: ( "", 'ARABIC LIGATURE MEEM WITH KHAH WITH JEEM INITIAL FORM' ),
        0xfd8f: ( "", 'ARABIC LIGATURE MEEM WITH KHAH WITH MEEM INITIAL FORM' ),
        0xfd92: ( "", 'ARABIC LIGATURE MEEM WITH JEEM WITH KHAH INITIAL FORM' ),
        0xfd93: ( "", 'ARABIC LIGATURE HEH WITH MEEM WITH JEEM INITIAL FORM' ),
        0xfd94: ( "", 'ARABIC LIGATURE HEH WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd95: ( "", 'ARABIC LIGATURE NOON WITH HAH WITH MEEM INITIAL FORM' ),
        0xfd96: ( "", 'ARABIC LIGATURE NOON WITH HAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfd97: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH MEEM FINAL FORM' ),
        0xfd98: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH MEEM INITIAL FORM' ),
        0xfd99: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd9a: ( "", 'ARABIC LIGATURE NOON WITH MEEM WITH YEH FINAL FORM' ),
        0xfd9b: ( "", 'ARABIC LIGATURE NOON WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfd9c: ( "", 'ARABIC LIGATURE YEH WITH MEEM WITH MEEM FINAL FORM' ),
        0xfd9d: ( "", 'ARABIC LIGATURE YEH WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfd9e: ( "", 'ARABIC LIGATURE BEH WITH KHAH WITH YEH FINAL FORM' ),
        0xfd9f: ( "", 'ARABIC LIGATURE TEH WITH JEEM WITH YEH FINAL FORM' ),
        0xfda0: ( "", 'ARABIC LIGATURE TEH WITH JEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfda1: ( "", 'ARABIC LIGATURE TEH WITH KHAH WITH YEH FINAL FORM' ),
        0xfda2: ( "", 'ARABIC LIGATURE TEH WITH KHAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfda3: ( "", 'ARABIC LIGATURE TEH WITH MEEM WITH YEH FINAL FORM' ),
        0xfda4: ( "", 'ARABIC LIGATURE TEH WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfda5: ( "", 'ARABIC LIGATURE JEEM WITH MEEM WITH YEH FINAL FORM' ),
        0xfda6: ( "", 'ARABIC LIGATURE JEEM WITH HAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfda7: ( "", 'ARABIC LIGATURE JEEM WITH MEEM WITH ALEF MAKSURA FINAL FORM' ),
        0xfda8: ( "", 'ARABIC LIGATURE SEEN WITH KHAH WITH ALEF MAKSURA FINAL FORM' ),
        0xfda9: ( "", 'ARABIC LIGATURE SAD WITH HAH WITH YEH FINAL FORM' ),
        0xfdaa: ( "", 'ARABIC LIGATURE SHEEN WITH HAH WITH YEH FINAL FORM' ),
        0xfdab: ( "", 'ARABIC LIGATURE DAD WITH HAH WITH YEH FINAL FORM' ),
        0xfdac: ( "", 'ARABIC LIGATURE LAM WITH JEEM WITH YEH FINAL FORM' ),
        0xfdad: ( "", 'ARABIC LIGATURE LAM WITH MEEM WITH YEH FINAL FORM' ),
        0xfdae: ( "", 'ARABIC LIGATURE YEH WITH HAH WITH YEH FINAL FORM' ),
        0xfdaf: ( "", 'ARABIC LIGATURE YEH WITH JEEM WITH YEH FINAL FORM' ),
        0xfdb0: ( "", 'ARABIC LIGATURE YEH WITH MEEM WITH YEH FINAL FORM' ),
        0xfdb1: ( "", 'ARABIC LIGATURE MEEM WITH MEEM WITH YEH FINAL FORM' ),
        0xfdb2: ( "", 'ARABIC LIGATURE QAF WITH MEEM WITH YEH FINAL FORM' ),
        0xfdb3: ( "", 'ARABIC LIGATURE NOON WITH HAH WITH YEH FINAL FORM' ),
        0xfdb4: ( "", 'ARABIC LIGATURE QAF WITH MEEM WITH HAH INITIAL FORM' ),
        0xfdb5: ( "", 'ARABIC LIGATURE LAM WITH HAH WITH MEEM INITIAL FORM' ),
        0xfdb6: ( "", 'ARABIC LIGATURE AIN WITH MEEM WITH YEH FINAL FORM' ),
        0xfdb7: ( "", 'ARABIC LIGATURE KAF WITH MEEM WITH YEH FINAL FORM' ),
        0xfdb8: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH HAH INITIAL FORM' ),
        0xfdb9: ( "", 'ARABIC LIGATURE MEEM WITH KHAH WITH YEH FINAL FORM' ),
        0xfdba: ( "", 'ARABIC LIGATURE LAM WITH JEEM WITH MEEM INITIAL FORM' ),
        0xfdbb: ( "", 'ARABIC LIGATURE KAF WITH MEEM WITH MEEM FINAL FORM' ),
        0xfdbc: ( "", 'ARABIC LIGATURE LAM WITH JEEM WITH MEEM FINAL FORM' ),
        0xfdbd: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH HAH FINAL FORM' ),
        0xfdbe: ( "", 'ARABIC LIGATURE JEEM WITH HAH WITH YEH FINAL FORM' ),
        0xfdbf: ( "", 'ARABIC LIGATURE HAH WITH JEEM WITH YEH FINAL FORM' ),
        0xfdc0: ( "", 'ARABIC LIGATURE MEEM WITH JEEM WITH YEH FINAL FORM' ),
        0xfdc1: ( "", 'ARABIC LIGATURE FEH WITH MEEM WITH YEH FINAL FORM' ),
        0xfdc2: ( "", 'ARABIC LIGATURE BEH WITH HAH WITH YEH FINAL FORM' ),
        0xfdc3: ( "", 'ARABIC LIGATURE KAF WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfdc4: ( "", 'ARABIC LIGATURE AIN WITH JEEM WITH MEEM INITIAL FORM' ),
        0xfdc5: ( "", 'ARABIC LIGATURE SAD WITH MEEM WITH MEEM INITIAL FORM' ),
        0xfdc6: ( "", 'ARABIC LIGATURE SEEN WITH KHAH WITH YEH FINAL FORM' ),
        0xfdc7: ( "", 'ARABIC LIGATURE NOON WITH JEEM WITH YEH FINAL FORM' ),
        0xfdf0: ( "", 'ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM' ),
        0xfdf1: ( "", 'ARABIC LIGATURE QALA USED AS KORANIC STOP SIGN ISOLATED FORM' ),
        0xfdf2: ( "", 'ARABIC LIGATURE ALLAH ISOLATED FORM' ),
        0xfdf3: ( "", 'ARABIC LIGATURE AKBAR ISOLATED FORM' ),
        0xfdf4: ( "", 'ARABIC LIGATURE MOHAMMAD ISOLATED FORM' ),
        0xfdf5: ( "", 'ARABIC LIGATURE SALAM ISOLATED FORM' ),
        0xfdf6: ( "", 'ARABIC LIGATURE RASOUL ISOLATED FORM' ),
        0xfdf7: ( "", 'ARABIC LIGATURE ALAYHE ISOLATED FORM' ),
        0xfdf8: ( "", 'ARABIC LIGATURE WASALLAM ISOLATED FORM' ),
        0xfdf9: ( "", 'ARABIC LIGATURE SALLA ISOLATED FORM' ),
        0xfdfa: ( "", 'ARABIC LIGATURE SALLALLAHOU ALAYHE WASALLAM' ),
        0xfdfb: ( "", 'ARABIC LIGATURE JALLAJALALOUHOU' ),
        0xfdfd: ( "", 'ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM' ),
        0xfe20: ( "", 'COMBINING LIGATURE LEFT HALF' ),
        0xfe21: ( "", 'COMBINING LIGATURE RIGHT HALF' ),
        0xfef5: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM' ),
        0xfef6: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM' ),
        0xfef7: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM' ),
        0xfef8: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM' ),
        0xfef9: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM' ),
        0xfefa: ( "", 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM' ),
        0xfefb: ( "", 'ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM' ),
        0xfefc: ( "", 'ARABIC LIGATURE LAM WITH ALEF FINAL FORM' ),
        }

        # Add? Control pix, combiners

        return  # End __init__


###############################################################################
###############################################################################
# Main
#
if __name__ == "__main__":
    def processOptions():
        try:
            from MarkupHelpFormatter import MarkupHelpFormatter
            formatter = MarkupHelpFormatter
        except ImportError:
            formatter = None
        parser = argparse.ArgumentParser(
            description=descr, formatter_class=formatter)

        parser.add_argument(
            "--quiet", "-q",      action='store_true',
            help='Suppress most messages.')
        parser.add_argument(
            "--verbose", "-v",    action='count',       default=0,
            help='Add more messages (repeatable).')
        parser.add_argument(
            "--version", action='version', version=__version__,
            help='Display version information, then exit.')

        parser.add_argument(
            'files',             type=str,
            nargs=argparse.REMAINDER,
            help='Path(s) to input file(s)')

        args0 = parser.parse_args()
        return(args0)

    ###########################################################################
    #
    args = processOptions()
    print("Testing...")

