    # Which side does each one go on, and how does Bengali work?
    currency = [
        0x00A3:  ( "L", "POUND SIGN" ),
        0x00A4:  ( "L", "CURRENCY SIGN" ),
        0x09F4:  ( "?", "Bengali currency numerators/denominator" ),
        0x09F5:  ( "?", "Bengali currency numerators/denominator" ),
        0x09F6:  ( "?", "Bengali currency numerators/denominator" ),
        0x09F7:  ( "?", "Bengali currency numerators/denominator" ),
        0x09F8:  ( "?", "Bengali currency numerators/denominator" ),
        0x09F9:  ( "?", "Bengali currency numerators/denominator" ),
        0x0E3F:  ( "?", "THAI BHAT" ),
        0x17DB:  ( "?", "KHMER RIEL" ),

        0x20A0:  ( "?", "EURO-CURRENCY SIGN" ),
        0x20A1:  ( "?", "COLON SIGN" ),
        0x20A2:  ( "?", "CRUZEIRO SIGN" ),
        0x20A3:  ( "?", "FRENCH FRANC SIGN" ),
        0x20A4:  ( "?", "LIRA SIGN" ),
        0x20A5:  ( "?", "MILL SIGN" ),
        0x20A6:  ( "?", "NAIRA SIGN" ),
        0x20A7:  ( "?", "PESETA SIGN" ),
        0x20A8:  ( "?", "RUPEE SIGN" ),
        0x20A9:  ( "?", "WON SIGN" ),
        0x20AA:  ( "?", "NEW SHEQEL SIGN" ),
        0x20AB:  ( "?", "DONG SIGN" ),
        0x20AC:  ( "?", "EURO SIGN" ),
        0x20AD:  ( "?", "KIP SIGN" ),
        0x20AE:  ( "?", "TUGRIK SIGN" ),
        0x20AF:  ( "?", "DRACHMA SIGN" ),
        0x20B0:  ( "?", "GERMAN PENNY SIGN" ),
        0x20B1:  ( "?", "PESO SIGN" ),
        0x20B2:  ( "?", "GUARANI SIGN" ),
        0x20B3:  ( "?", "AUSTRAL SIGN" ),
        0x20B4:  ( "?", "HRYVNIA SIGN" ),
        0x20B5:  ( "?", "CEDI SIGN" ),
        0x20B6:  ( "?", "LIVRE TOURNOIS SIGN" ),
        0x20B7:  ( "?", "SPESMILO SIGN" ),
        0x20B8:  ( "?", "TENGE SIGN" ),
        0x20B9:  ( "?", "INDIAN RUPEE SIGN" ),
        0x20BA:  ( "?", "TURKISH LIRA SIGN" ),

        0xFFE1:  ( "L", "FULLWIDTH POUND SIGN" ),
        0xFE69:  ( "L", "SMALL DOLLAR SIGN" ),
        0xFF04:  ( "L", "FULLWIDTH DOLLAR SIGN" ),
        0x1F4B2: ( "L", "HEAVY DOLLAR SIGN" ),
    ]
