# See also UnicodeSpecials.py
    fractions = {
        #0x2044: "FRACTION SLASH",

        0x00BC: "VULGAR FRACTION ONE QUARTER",
        0x00BD: "VULGAR FRACTION ONE HALF",
        0x00BE: "VULGAR FRACTION THREE QUARTERS",
        0x2150: "VULGAR FRACTION ONE SEVENTH",
        0x2151: "VULGAR FRACTION ONE NINTH",
        0x2152: "VULGAR FRACTION ONE TENTH",
        0x2153: "VULGAR FRACTION ONE THIRD",
        0x2154: "VULGAR FRACTION TWO THIRDS",
        0x2155: "VULGAR FRACTION ONE FIFTH",
        0x2156: "VULGAR FRACTION TWO FIFTHS",
        0x2157: "VULGAR FRACTION THREE FIFTHS",
        0x2158: "VULGAR FRACTION FOUR FIFTHS",
        0x2159: "VULGAR FRACTION ONE SIXTH",
        0x215A: "VULGAR FRACTION FIVE SIXTHS",
        0x215B: "VULGAR FRACTION ONE EIGHTH",
        0x215C: "VULGAR FRACTION THREE EIGHTHS",
        0x215D: "VULGAR FRACTION FIVE EIGHTHS",
        0x215E: "VULGAR FRACTION SEVEN EIGHTHS",
        0x2189: "VULGAR FRACTION ZERO THIRDS",

        0x0B72: "ORIYA FRACTION ONE QUARTER",
        0x0B73: "ORIYA FRACTION ONE HALF",
        0x0B74: "ORIYA FRACTION THREE QUARTERS",
        0x0B75: "ORIYA FRACTION ONE SIXTEENTH",
        0x0B76: "ORIYA FRACTION ONE EIGHTH",
        0x0B77: "ORIYA FRACTION THREE SIXTEENTHS",

        0x0C78: "TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR",
        0x0C79: "TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR",
        0x0C7A: "TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR",
        0x0C7B: "TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR",
        0x0C7C: "TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR",
        0x0C7D: "TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR",
        0x0C7E: "TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR",

        0x0D73: "MALAYALAM FRACTION ONE QUARTER",
        0x0D74: "MALAYALAM FRACTION ONE HALF",
        0x0D75: "MALAYALAM FRACTION THREE QUARTERS",

        0x215F: "FRACTION NUMERATOR ONE",

        0x2CFD: "COPTIC FRACTION ONE HALF",

        0xA830: "NORTH INDIC FRACTION ONE QUARTER",
        0xA831: "NORTH INDIC FRACTION ONE HALF",
        0xA832: "NORTH INDIC FRACTION THREE QUARTERS",
        0xA833: "NORTH INDIC FRACTION ONE SIXTEENTH",
        0xA834: "NORTH INDIC FRACTION ONE EIGHTH",
        0xA835: "NORTH INDIC FRACTION THREE SIXTEENTHS",

        0x10E7B: "RUMI FRACTION ONE HALF",
        0x10E7C: "RUMI FRACTION ONE QUARTER",
        0x10E7D: "RUMI FRACTION ONE THIRD",
        0x10E7E: "RUMI FRACTION TWO THIRDS",
    }
