sentenceBounds = [
U+003f	?	QUESTION MARK
U+00bf	¿	INVERTED QUESTION MARK
U+037e	;	GREEK QUESTION MARK
U+055e	՞	ARMENIAN QUESTION MARK
U+061f	؟	ARABIC QUESTION MARK
U+1367	፧	ETHIOPIC QUESTION MARK
U+1945	᥅	LIMBU QUESTION MARK
U+2047	⁇	DOUBLE QUESTION MARK
U+2048	⁈	QUESTION EXCLAMATION MARK
U+2049	⁉	EXCLAMATION QUESTION MARK
U+2753	❓	BLACK QUESTION MARK ORNAMENT
U+2754	❔	WHITE QUESTION MARK ORNAMENT
U+2cfa	⳺	COPTIC OLD NUBIAN DIRECT QUESTION MARK
U+2cfb	⳻	COPTIC OLD NUBIAN INDIRECT QUESTION MARK
U+2e2e	⸮	REVERSED QUESTION MARK
U+3244	㉄	CIRCLED IDEOGRAPH QUESTION
U+a60f	꘏	VAI QUESTION MARK
U+a6f7	꛷	BAMUM QUESTION MARK
U+fe16	︖	PRESENTATION FORM FOR VERTICAL QUESTION MARK
U+fe56	﹖	SMALL QUESTION MARK
U+ff1f	？	FULLWIDTH QUESTION MARK

U+0021	!	EXCLAMATION MARK
U+00a1	¡	INVERTED EXCLAMATION MARK
U+055c	՜	ARMENIAN EXCLAMATION MARK
U+07f9	߹	NKO EXCLAMATION MARK
U+109f	႟	MYANMAR SYMBOL SHAN EXCLAMATION
U+1944	᥄	LIMBU EXCLAMATION MARK
U+203c	‼	DOUBLE EXCLAMATION MARK
U+2048	⁈	QUESTION EXCLAMATION MARK
U+2049	⁉	EXCLAMATION QUESTION MARK
U+2755	❕	WHITE EXCLAMATION MARK ORNAMENT
U+2757	❗	HEAVY EXCLAMATION MARK SYMBOL
U+2762	❢	HEAVY EXCLAMATION MARK ORNAMENT
U+2763	❣	HEAVY HEART EXCLAMATION MARK ORNAMENT
U+aa77	꩷	MYANMAR SYMBOL AITON EXCLAMATION
U+fe15	︕	PRESENTATION FORM FOR VERTICAL EXCLAMATION MARK
U+fe57	﹗	SMALL EXCLAMATION MARK
U+ff01	！	FULLWIDTH EXCLAMATION MARK

U+0eaf	ຯ	LAO ELLIPSIS
U+1801	᠁	MONGOLIAN ELLIPSIS
U+2026	…	HORIZONTAL ELLIPSIS
U+2118	℘	WEIERSTRASS ELLIPTIC FUNCTION
U+22ee	⋮	VERTICAL ELLIPSIS
U+22ef	⋯	MIDLINE HORIZONTAL ELLIPSIS
U+fe19	︙	PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS

U+002e	.	FULL STOP
U+0589	։	ARMENIAN FULL STOP
U+06d4	۔	ARABIC FULL STOP
U+06ea 	۪	ARABIC EMPTY CENTRE LOW STOP
U+06eb 	۫	ARABIC EMPTY CENTRE HIGH STOP
U+06ec 	۬	ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE
U+0701	܁	SYRIAC SUPRALINEAR FULL STOP
U+0702	܂	SYRIAC SUBLINEAR FULL STOP
U+1362	።	ETHIOPIC FULL STOP
U+166e	᙮	CANADIAN SYLLABICS FULL STOP
U+1803	᠃	MONGOLIAN FULL STOP
U+1809	᠉	MONGOLIAN MANCHU FULL STOP
U+2488	⒈	DIGIT ONE FULL STOP
U+2489	⒉	DIGIT TWO FULL STOP
U+248a	⒊	DIGIT THREE FULL STOP
U+248b	⒋	DIGIT FOUR FULL STOP
U+248c	⒌	DIGIT FIVE FULL STOP
U+248d	⒍	DIGIT SIX FULL STOP
U+248e	⒎	DIGIT SEVEN FULL STOP
U+248f	⒏	DIGIT EIGHT FULL STOP
U+2490	⒐	DIGIT NINE FULL STOP
U+2491	⒑	NUMBER TEN FULL STOP
U+2492	⒒	NUMBER ELEVEN FULL STOP
U+2493	⒓	NUMBER TWELVE FULL STOP
U+2494	⒔	NUMBER THIRTEEN FULL STOP
U+2495	⒕	NUMBER FOURTEEN FULL STOP
U+2496	⒖	NUMBER FIFTEEN FULL STOP
U+2497	⒗	NUMBER SIXTEEN FULL STOP
U+2498	⒘	NUMBER SEVENTEEN FULL STOP
U+2499	⒙	NUMBER EIGHTEEN FULL STOP
U+249a	⒚	NUMBER NINETEEN FULL STOP
U+249b	⒛	NUMBER TWENTY FULL STOP
U+2cf9	⳹	COPTIC OLD NUBIAN FULL STOP
U+2cfe	⳾	COPTIC FULL STOP
U+3002	。	IDEOGRAPHIC FULL STOP
U+a4ff	꓿	LISU PUNCTUATION FULL STOP
U+a60e	꘎	VAI FULL STOP
U+a6f3	꛳	BAMUM FULL STOP
U+fdf0	ﷰ	ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM
U+fdf1	ﷱ	ARABIC LIGATURE QALA USED AS KORANIC STOP SIGN ISOLATED FORM
U+fe12	︒	PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC FULL STOP
U+fe52	﹒	SMALL FULL STOP
U+ff0e	．	FULLWIDTH FULL STOP
U+ff61	｡	HALFWIDTH IDEOGRAPHIC FULL STOP

¶
