#
#pylint: disable=C0301
#
# A list of the Unicode blocks, with their ranges of codepoints and
# a language code for what language writes with them, as best I can figure.
#
# The Language codes are from ISO 639-3 except for these (which
# all start with "_", unlike any ISO 639 codes):
#     "_ID" for CJK ideographic orthogrpahies
#     "_CY" for Cyrillic
#     "_MA" for math
#     "_MU" for music
#     "_GA" for gaming symbols
#     "_PH" for phonetic symbols
#     "_FO" for formatting variants
#     "_??" intended for NL orthographies for which I cannot choose a lg code
#         This includes CJK and Cyrillic.
#
# One goal was to have an easy way to sort out the "linguistic" blocks from
# others, and to group extensions and supplements with their basic block.
# Caveat: I don't know most of these languages or their sociopolitical status.
# For most, I just matched names vs. ISO 639-3. In some cases, I couldn't find
# the language in ISO 639-3, or even be certain the block is associated with a
# language(s) at all. In such cases I've made my best guess and marked them "_??".
#
# History:
#     2023-05-03: Assembled by Steven J. DeRose, sderose@acm.org.
#

UnicodeBlocks = {
    # Block name                         start   end     LG     name
    "Basic Latin":                      (0x0000, 0x007F, "LAT", "Basic Latin"),
    "Latin-1 Supplement":               (0x0080, 0x00FF, "LAT", "Latin-1 Supplement"),
    "Latin Extended-A":                 (0x0100, 0x017F, "LAT", "Latin Extended-A"),
    "Latin Extended-B":                 (0x0180, 0x024F, "LAT", "Latin Extended-B"),
    "IPA Extensions":                   (0x0250, 0x02AF, "_PH", "IPA Extensions"),
    "Spacing Modifier Letters":         (0x02B0, 0x02FF, "_FO", "Spacing Modifier Letters"),
    "Combining Diacritical Marks":      (0x0300, 0x036F, "",    "Combining Diacritical Marks"),
    "Greek and Coptic":                 (0x0370, 0x03FF, "ELL", "Greek and Coptic"),
    "Cyrillic":                         (0x0400, 0x04FF, "_CY", "Cyrillic"),
    "Cyrillic Supplement":              (0x0500, 0x052F, "_CY", "Cyrillic Supplement"),
    "Armenian":                         (0x0530, 0x058F, "HYE", "Armenian"),
    "Hebrew":                           (0x0590, 0x05FF, "HEB", "Hebrew"),
    "Arabic":                           (0x0600, 0x06FF, "ARA", "Arabic"),
    "Syriac":                           (0x0700, 0x074F, "SYC", "Syriac"),
    "Arabic Supplement":                (0x0750, 0x077F, "ARA", "Arabic Supplement"),
    "Thaana":                           (0x0780, 0x07BF, "_??", "Thaana"),
    "NKo":                              (0x07C0, 0x07FF, "_??", "NKo"),
    "Samaritan":                        (0x0800, 0x083F, "SAM", "Samaritan"),
    "Mandaic":                          (0x0840, 0x085F, "MID", "Mandaic"),
    "Syriac Supplement":                (0x0860, 0x086F, "SYC", "Syriac Supplement"),
    "Arabic Extended-A":                (0x08A0, 0x08FF, "ARA", "Arabic Extended-A"),
    "Devanagari":                       (0x0900, 0x097F, "_??", "Devanagari"),
    "Bengali":                          (0x0980, 0x09FF, "BEN", "Bengali"),
    "Gurmukhi":                         (0x0A00, 0x0A7F, "_??", "Gurmukhi"),
    "Gujarati":                         (0x0A80, 0x0AFF, "GUJ", "Gujarati"),
    "Oriya":                            (0x0B00, 0x0B7F, "ORI", "Oriya"),
    "Tamil":                            (0x0B80, 0x0BFF, "TAM", "Tamil"),
    "Telugu":                           (0x0C00, 0x0C7F, "TEL", "Telugu"),
    "Kannada":                          (0x0C80, 0x0CFF, "KAN", "Kannada"),
    "Malayalam":                        (0x0D00, 0x0D7F, "MAL", "Malayalam"),
    "Sinhala":                          (0x0D80, 0x0DFF, "SIN", "Sinhala"),
    "Thai":                             (0x0E00, 0x0E7F, "THA", "Thai"),
    "Lao":                              (0x0E80, 0x0EFF, "LAO", "Lao"),
    "Tibetan":                          (0x0F00, 0x0FFF, "BOD", "Tibetan"),
    "Myanmar":                          (0x1000, 0x109F, "_??", "Myanmar"),
    "Georgian":                         (0x10A0, 0x10FF, "KAT", "Georgian"),
    "Hangul Jamo":                      (0x1100, 0x11FF, "_??", "Hangul Jamo"),
    "Ethiopic":                         (0x1200, 0x137F, "_??", "Ethiopic"),
    "Ethiopic Supplement":              (0x1380, 0x139F, "_??", "Ethiopic Supplement"),
    "Cherokee":                         (0x13A0, 0x13FF, "CHR", "Cherokee"),
    "Unified Canadian Aboriginal Syllabics":
                                        (0x1400, 0x167F, "_??", "Unified Canadian Aboriginal Syllabics"),
    "Ogham":                            (0x1680, 0x169F, "_??", "Ogham"),  # Early irish orthography
    "Runic":                            (0x16A0, 0x16FF, "_??", "Runic"),  # Early Norse
    "Tagalog":                          (0x1700, 0x171F, "TGL", "Tagalog"),
    "Hanunoo":                          (0x1720, 0x173F, "HNN", "Hanunoo"),
    "Buhid":                            (0x1740, 0x175F, "BKU", "Buhid"),
    "Tagbanwa":                         (0x1760, 0x177F, "TBW", "Tagbanwa"),
    "Khmer":                            (0x1780, 0x17FF, "KHM", "Khmer"),
    "Mongolian":                        (0x1800, 0x18AF, "MON", "Mongolian"),
    "Unified Canadian Aboriginal Syllabics Extended":
                                        (0x18B0, 0x18FF, "_??", "Unified Canadian Aboriginal Syllabics Extended"),
    "Limbu":                            (0x1900, 0x194F, "LIF", "Limbu"),
    "Tai Le":                           (0x1950, 0x197F, "_??", "Tai Le"),
    "New Tai Lue":                      (0x1980, 0x19DF, "_??", "New Tai Lue"),
    "Khmer Symbols":                    (0x19E0, 0x19FF, "_??", "Khmer Symbols"),
    "Buginese":                         (0x1A00, 0x1A1F, "BUG", "Buginese"),
    "Tai Tham":                         (0x1A20, 0x1AAF, "_??", "Tai Tham"),
    "Combining Diacritical Marks Extended":
                                        (0x1AB0, 0x1AFF, "",    "Combining Diacritical Marks Extended"),
    "Balinese":                         (0x1B00, 0x1B7F, "BAN", "Balinese"),
    "Sundanese":                        (0x1B80, 0x1BBF, "SUN", "Sundanese"),
    "Batak":                            (0x1BC0, 0x1BFF, "BYA", "Batak"),
    "Lepcha":                           (0x1C00, 0x1C4F, "LEP", "Lepcha"),
    "Ol Chiki":                         (0x1C50, 0x1C7F, "_??", "Ol Chiki"),
    "Cyrillic Extended-C":              (0x1C80, 0x1C8F, "_CY", "Cyrillic Extended-C"),
    "Sundanese Supplement":             (0x1CC0, 0x1CCF, "SUN", "Sundanese Supplement"),
    "Vedic Extensions":                 (0x1CD0, 0x1CFF, "_??", "Vedic Extensions"),
    "Phonetic Extensions":              (0x1D00, 0x1D7F, "_PH", "Phonetic Extensions"),
    "Phonetic Extensions Supplement":   (0x1D80, 0x1DBF, "_PH", "Phonetic Extensions Supplement"),
    "Combining Diacritical Marks Supplement":
                                        (0x1DC0, 0x1DFF, "",    "Combining Diacritical Marks Supplement"),
    "Latin Extended Additional":        (0x1E00, 0x1EFF, "LAT", "Latin Extended Additional"),
    "Greek Extended":                   (0x1F00, 0x1FFF, "ELL", "Greek Extended"),
    "General Punctuation":              (0x2000, 0x206F, "",    "General Punctuation"),
    "Superscripts and Subscripts":      (0x2070, 0x209F, "_FO", "Superscripts and Subscripts"),
    "Currency Symbols":                 (0x20A0, 0x20CF, "",    "Currency Symbols"),
    "Combining Diacritical Marks for Symbols":
                                        (0x20D0, 0x20FF, "",    "Combining Diacritical Marks for Symbols"),
    "Letterlike Symbols":               (0x2100, 0x214F, "",    "Letterlike Symbols"),
    "Number Forms":                     (0x2150, 0x218F, "_FO", "Number Forms"),
    "Arrows":                           (0x2190, 0x21FF, "",    "Arrows"),
    "Mathematical Operators":           (0x2200, 0x22FF, "_MA", "Mathematical Operators"),
    "Miscellaneous Technical":          (0x2300, 0x23FF, "",    "Miscellaneous Technical"),
    "Control Pictures":                 (0x2400, 0x243F, "_FO", "Control Pictures"),
    "Optical Character Recognition":    (0x2440, 0x245F, "_FO", "Optical Character Recognition"),
    "Enclosed Alphanumerics":           (0x2460, 0x24FF, "_FO", "Enclosed Alphanumerics"),
    "Box Drawing":                      (0x2500, 0x257F, "_FO", "Box Drawing"),
    "Block Elements":                   (0x2580, 0x259F, "",    "Block Elements"),
    "Geometric Shapes":                 (0x25A0, 0x25FF, "",    "Geometric Shapes"),
    "Miscellaneous Symbols":            (0x2600, 0x26FF, "",    "Miscellaneous Symbols"),
    "Dingbats":                         (0x2700, 0x27BF, "",    "Dingbats"),
    "Miscellaneous Mathematical Symbols-A":
                                        (0x27C0, 0x27EF, "_MA", "Miscellaneous Mathematical Symbols-A"),
    "Supplemental Arrows-A":
                                        (0x27F0, 0x27FF, "",    "Supplemental Arrows-A"),
    "Braille Patterns":
                                        (0x2800, 0x28FF, "",    "Braille Patterns"),
    "Supplemental Arrows-B":
                                        (0x2900, 0x297F, "",    "Supplemental Arrows-B"),
    "Miscellaneous Mathematical Symbols-B":
                                        (0x2980, 0x29FF, "_MA", "Miscellaneous Mathematical Symbols-B"),
    "Supplemental Mathematical Operators":
                                        (0x2A00, 0x2AFF, "_MA", "Supplemental Mathematical Operators"),
    "Miscellaneous Symbols and Arrows":
                                        (0x2B00, 0x2BFF, "",    "Miscellaneous Symbols and Arrows"),
    "Glagolitic":                       (0x2C00, 0x2C5F, "_??", "Glagolitic"),
    "Latin Extended-C":                 (0x2C60, 0x2C7F, "LAT", "Latin Extended-C"),
    "Coptic":                           (0x2C80, 0x2CFF, "_??", "Coptic"),
    "Georgian Supplement":              (0x2D00, 0x2D2F, "_??", "Georgian Supplement"),
    "Tifinagh":                         (0x2D30, 0x2D7F, "_??", "Tifinagh"),
    "Ethiopic Extended":                (0x2D80, 0x2DDF, "_??", "Ethiopic Extended"),
    "Cyrillic Extended-A":              (0x2DE0, 0x2DFF, "_CY", "Cyrillic Extended-A"),
    "Supplemental Punctuation":         (0x2E00, 0x2E7F, "",    "Supplemental Punctuation"),
    "CJK Radicals Supplement":          (0x2E80, 0x2EFF, "_ID", "CJK Radicals Supplement"),
    "Kangxi Radicals":                  (0x2F00, 0x2FDF, "_??", "Kangxi Radicals"),
    "Ideographic Description Characters":
                                        (0x2FF0, 0x2FFF, "",    "Ideographic Description Characters"),
    "CJK Symbols and Punctuation":      (0x3000, 0x303F, "_ID", "CJK Symbols and Punctuation"),
    "Hiragana":                         (0x3040, 0x309F, "JPN", "Hiragana"),
    "Katakana":                         (0x30A0, 0x30FF, "JPN", "Katakana"),
    "Bopomofo":                         (0x3100, 0x312F, "_??", "Bopomofo"),
    "Hangul Compatibility Jamo":        (0x3130, 0x318F, "_??", "Hangul Compatibility Jamo"),
    "Kanbun":                           (0x3190, 0x319F, "_??", "Kanbun"),
    "Bopomofo Extended":                (0x31A0, 0x31BF, "_??", "Bopomofo Extended"),
    "CJK Strokes":                      (0x31C0, 0x31EF, "_ID", "CJK Strokes"),
    "Katakana Phonetic Extensions":     (0x31F0, 0x31FF, "_PH", "Katakana Phonetic Extensions"),
    "Enclosed CJK Letters and Months":  (0x3200, 0x32FF, "_FO", ""),
    "CJK Compatibility":                (0x3300, 0x33FF, "_ID", "CJK Compatibility"),
    "CJK Unified Ideographs Extension A":
                                        (0x3400, 0x4DBF, "_ID", "CJK Unified Ideographs Extension A"),
    "Yijing Hexagram Symbols":          (0x4DC0, 0x4DFF, "",    "Yijing Hexagram Symbols"),
    "CJK Unified Ideographs":           (0x4E00, 0x9FFF, "_ID", "CJK Unified Ideographs"),
    "Yi Syllables":                     (0xA000, 0xA48F, "",    "Yi Syllables"),
    "Yi Radicals":                      (0xA490, 0xA4CF, "",    "Yi Radicals"),
    "Lisu":                             (0xA4D0, 0xA4FF, "LIS", "Lisu"),
    "Vai":                              (0xA500, 0xA63F, "VAI", "Vai"),
    "Cyrillic Extended-B":              (0xA640, 0xA69F, "_CY", "Cyrillic Extended-B"),
    "Bamum":                            (0xA6A0, 0xA6FF, "_??", "Bamum"),
    "Modifier Tone Letters":            (0xA700, 0xA71F, "",    "Modifier Tone Letters"),
    "Latin Extended-D":                 (0xA720, 0xA7FF, "LAT", "Latin Extended-D"),
    "Syloti Nagri":                     (0xA800, 0xA82F, "_??", "Syloti Nagri"),
    "Common Indic Number Forms":        (0xA830, 0xA83F, "_MA", "Common Indic Number Forms"),
    "Phags-pa":                         (0xA840, 0xA87F, "_??", "Phags-pa"),
    "Saurashtra":                       (0xA880, 0xA8DF, "SAZ", "Saurashtra"),
    "Devanagari Extended":              (0xA8E0, 0xA8FF, "_??", "Devanagari Extended"),
    "Kayah Li":                         (0xA900, 0xA92F, "_??", "Kayah Li"),
    "Rejang":                           (0xA930, 0xA95F, "REJ", "Rejang"),
    "Hangul Jamo Extended-A":           (0xA960, 0xA97F, "_??", "Hangul Jamo Extended-A"),
    "Javanese":                         (0xA980, 0xA9DF, "JAV", "Javanese"),
    "Myanmar Extended-B":               (0xA9E0, 0xA9FF, "_??", "Myanmar Extended-B"),
    "Cham":                             (0xAA00, 0xAA5F, "_??", "Cham"),
    "Myanmar Extended-A":               (0xAA60, 0xAA7F, "_??", "Myanmar Extended-A"),
    "Tai Viet":                         (0xAA80, 0xAADF, "_??", "Tai Viet"),
    "Meetei Mayek Extensions":          (0xAAE0, 0xAAFF, "_??", "Meetei Mayek Extensions"),
    "Ethiopic Extended-A":              (0xAB00, 0xAB2F, "_??", "Ethiopic Extended-A"),
    "Latin Extended-E":                 (0xAB30, 0xAB6F, "LAT", "Latin Extended-E"),
    "Cherokee Supplement":              (0xAB70, 0xABBF, "CHR", "Cherokee Supplement"),
    "Meetei Mayek":                     (0xABC0, 0xABFF, "_??", "Meetei Mayek"),
    "Hangul Syllables":                 (0xAC00, 0xD7AF, "_??", "Hangul Syllables"),
    "Hangul Jamo Extended-B":           (0xD7B0, 0xD7FF, "_??", "Hangul Jamo Extended-B"),
    "High Surrogates":                  (0xD800, 0xDB7F, "",    "High Surrogates"),
    "High Private Use Surrogates":      (0xDB80, 0xDBFF, "",    "High Private Use Surrogates"),
    "Low Surrogates":                   (0xDC00, 0xDFFF, "",    "Low Surrogates"),
    "Private Use Area":                 (0xE000, 0xF8FF, "",    "Private Use Area"),
    "CJK Compatibility Ideographs":     (0xF900, 0xFAFF, "_ID", "CJK Compatibility Ideographs"),
    "Alphabetic Presentation Forms":    (0xFB00, 0xFB4F, "_FO", "Alphabetic Presentation Forms"),
    "Arabic Presentation Forms-A":      (0xFB50, 0xFDFF, "_FO", "Arabic Presentation Forms-A"),
    "Variation Selectors":              (0xFE00, 0xFE0F, "",    "Variation Selectors"),
    "Vertical Forms":                   (0xFE10, 0xFE1F, "_FO", "Vertical Forms"),
    "Combining Half Marks":             (0xFE20, 0xFE2F, "",    "Combining Half Marks"),
    "CJK Compatibility Forms":          (0xFE30, 0xFE4F, "_ID", "CJK Compatibility Forms"),
    "Small Form Variants":              (0xFE50, 0xFE6F, "_FO", "Small Form Variants"),
    "Arabic Presentation Forms-B":      (0xFE70, 0xFEFF, "_FO", "Arabic Presentation Forms-B"),
    "Halfwidth and Fullwidth Forms":    (0xFF00, 0xFFEF, "_FO", "Halfwidth and Fullwidth Forms"),
    "Specials":                         (0xFFF0, 0xFFFF, "",    "Specials"),
    #
    "Linear B Syllabary":               (0x10000, 0x1007F, "_??", "Linear B Syllabary"),
    "Linear B Ideograms":               (0x10080, 0x100FF, "_??", "Linear B Ideograms"),
    "Aegean Numbers":                   (0x10100, 0x1013F, "",    "Aegean Numbers"),
    "Ancient Greek Numbers":            (0x10140, 0x1018F, "",    "Ancient Greek Numbers"),
    "Ancient Symbols":                  (0x10190, 0x101CF, "",    "Ancient Symbols"),
    "Phaistos Disc":                    (0x101D0, 0x101FF, "",    "Phaistos Disc"),
    "Lycian":                           (0x10280, 0x1029F, "XLC", "Lycian"),
    "Carian":                           (0x102A0, 0x102DF, "XCR", "Carian"),
    "Coptic Epact Numbers":             (0x102E0, 0x102FF, "",    "Coptic Epact Numbers"),
    "Old Italic":                       (0x10300, 0x1032F, "_??", "Old Italic"),
    "Gothic":                           (0x10330, 0x1034F, "GOT", "Gothic"),
    "Old Permic":                       (0x10350, 0x1037F, "_??", "Old Permic"),
    "Ugaritic":                         (0x10380, 0x1039F, "UGA", "Ugaritic"),
    "Old Persian":                      (0x103A0, 0x103DF, "PEO", "Old Persian"),
    "Deseret":                          (0x10400, 0x1044F, "_??", "Deseret"),
    "Shavian":                          (0x10450, 0x1047F, "_??", "Shavian"),
    "Osmanya":                          (0x10480, 0x104AF, "_??", "Osmanya"),
    "Osage":                            (0x104B0, 0x104FF, "OSA", "Osage"),
    "Elbasan":                          (0x10500, 0x1052F, "_??", "Elbasan"),
    "Caucasian Albanian":               (0x10530, 0x1056F, "_??", "Caucasian Albanian"),
    "Linear A":                         (0x10600, 0x1077F, "_??", "Linear A"),
    "Cypriot Syllabary":                (0x10800, 0x1083F, "ACY", "Cypriot Syllabary"),  # ???
    "Imperial Aramaic":                 (0x10840, 0x1085F, "ARC", "Imperial Aramaic"),
    "Palmyrene":                        (0x10860, 0x1087F, "_??", "Palmyrene"),
    "Nabataean":                        (0x10880, 0x108AF, "_??", "Nabataean"),
    "Hatran":                           (0x108E0, 0x108FF, "_??", "Hatran"),
    "Phoenician":                       (0x10900, 0x1091F, "PHN", "Phoenician"),
    "Lydian":                           (0x10920, 0x1093F, "XLD", "Lydian"),
    "Meroitic Hieroglyphs":             (0x10980, 0x1099F, "XMR", "Meroitic Hieroglyphs"),
    "Meroitic Cursive":                 (0x109A0, 0x109FF, "XMR", "Meroitic Cursive"),
    "Kharoshthi":                       (0x10A00, 0x10A5F, "_??", "Kharoshthi"),  # Gandhari and Sanskrit 3-4c
    "Old South Arabian":                (0x10A60, 0x10A7F, "ARA", "Old South Arabian"),
    "Old North Arabian":                (0x10A80, 0x10A9F, "ARA", "Old North Arabian"),
    "Manichaean":                       (0x10AC0, 0x10AFF, "XMN", "Manichaean"),
    "Avestan":                          (0x10B00, 0x10B3F, "AVE", "Avestan"),
    "Inscriptional Parthian":           (0x10B40, 0x10B5F, "XPR", "Inscriptional Parthian"),
    "Inscriptional Pahlavi":            (0x10B60, 0x10B7F, "PAL", "Inscriptional Pahlavi"),
    "Psalter Pahlavi":                  (0x10B80, 0x10BAF, "PAL", "Psalter Pahlavi"),
    "Old Turkic":                       (0x10C00, 0x10C4F, "_??", "Old Turkic"),
    "Old Hungarian":                    (0x10C80, 0x10CFF, "OHU", "Old Hungarian"),
    "Rumi Numeral Symbols":             (0x10E60, 0x10E7F, "",    "Rumi Numeral Symbols"),
    "Brahmi":                           (0x11000, 0x1107F, "_??", "Brahmi"),
    "Kaithi":                           (0x11080, 0x110CF, "_??", "Kaithi"),
    "Sora Sompeng":                     (0x110D0, 0x110FF, "_??", "Sora Sompeng"),
    "Chakma":                           (0x11100, 0x1114F, "CCP", "Chakma"),
    "Mahajani":                         (0x11150, 0x1117F, "_??", "Mahajani"),
    "Sharada":                          (0x11180, 0x111DF, "_??", "Sharada"),
    "Sinhala Archaic Numbers":          (0x111E0, 0x111FF, "",    "Sinhala Archaic Numbers"),
    "Khojki":                           (0x11200, 0x1124F, "_??", "Khojki"),
    "Multani":                          (0x11280, 0x112AF, "_??", "Multani"),
    "Khudawadi":                        (0x112B0, 0x112FF, "_??", "Khudawadi"),
    "Grantha":                          (0x11300, 0x1137F, "_??", "Grantha"),
    "Newa":                             (0x11400, 0x1147F, "_??", "Newa"),  # ? newari
    "Tirhuta":                          (0x11480, 0x114DF, "_??", "Tirhuta"),
    "Siddham":                          (0x11580, 0x115FF, "_??", "Siddham"),
    "Modi":                             (0x11600, 0x1165F, "_??", "Modi"),
    "Mongolian Supplement":             (0x11660, 0x1167F, "MON", "Mongolian Supplement"),
    "Takri":                            (0x11680, 0x116CF, "_??", "Takri"),
    "Ahom":                             (0x11700, 0x1173F, "AHO", "Ahom"),
    "Warang Citi":                      (0x118A0, 0x118FF, "_??", "Warang Citi"),
    "Zanabazar Square":                 (0x11A00, 0x11A4F, "_??",    "Zanabazar Square"),  # Monglian, also Tibetan, Sanskrit
    "Soyombo":                          (0x11A50, 0x11AAF, "_??", "Soyombo"),
    "Pau Cin Hau":                      (0x11AC0, 0x11AFF, "_??", "Pau Cin Hau"),
    "Bhaiksuki":                        (0x11C00, 0x11C6F, "_??", "Bhaiksuki"),
    "Marchen":                          (0x11C70, 0x11CBF, "_??", "Marchen"),
    "Masaram Gondi":                    (0x11D00, 0x11D5F, "_??", "Masaram Gondi"),
    "Cuneiform":                        (0x12000, 0x123FF, "_??", "Cuneiform"),
    "Cuneiform Numbers and Punctuation":(0x12400, 0x1247F, "",    "Cuneiform Numbers and Punctuation"),
    "Early Dynastic Cuneiform":         (0x12480, 0x1254F, "_??", "Early Dynastic Cuneiform"),
    "Egyptian Hieroglyphs":             (0x13000, 0x1342F, "EGY", "Egyptian Hieroglyphs"),
    "Anatolian Hieroglyphs":            (0x14400, 0x1467F, "_??", "Anatolian Hieroglyphs"),
    "Bamum Supplement":                 (0x16800, 0x16A3F, "_??", "Bamum Supplement"),
    "Mro":                              (0x16A40, 0x16A6F, "_??", "Mro"),
    "Bassa Vah":                        (0x16AD0, 0x16AFF, "BSQ", "Bassa Vah"),  # ???
    "Pahawh Hmong":                     (0x16B00, 0x16B8F, "HMN", "Pahawh Hmong"),
    "Miao":                             (0x16F00, 0x16F9F, "_??", "Miao"),  # which to udse?
    "Ideographic Symbols and Punctuation":
                                        (0x16FE0, 0x16FFF, "",    "Ideographic Symbols and Punctuation"),
    "Tangut":                           (0x17000, 0x187FF, "TXG", "Tangut"),
    "Tangut Components":                (0x18800, 0x18AFF, "TXG", "Tangut Components"),
    "Kana Supplement":                  (0x1B000, 0x1B0FF, "JPN", "Kana Supplement"),
    "Kana Extended-A":                  (0x1B100, 0x1B12F, "JPN", "Kana Extended-A"),
    "Nushu":                            (0x1B170, 0x1B2FF, "_??", "Nushu"),
    "Duployan":                         (0x1BC00, 0x1BC9F, "_??", "Duployan"),
    "Shorthand Format Controls":        (0x1BCA0, 0x1BCAF, "_FO", "Shorthand Format Controls"),
    "Byzantine Musical Symbols":        (0x1D000, 0x1D0FF, "_MU", "Byzantine Musical Symbols"),
    "Musical Symbols":                  (0x1D100, 0x1D1FF, "_MU", "Musical Symbols"),
    "Ancient Greek Musical Notation":   (0x1D200, 0x1D24F, "_MU", "Ancient Greek Musical Notation"),
    "Tai Xuan Jing Symbols":            (0x1D300, 0x1D35F, "",    "Tai Xuan Jing Symbols"),
    "Counting Rod Numerals":            (0x1D360, 0x1D37F, "",    "Counting Rod Numerals"),
    "Mathematical Alphanumeric Symbols":(0x1D400, 0x1D7FF, "_MA", "Mathematical Alphanumeric Symbols"),
    "Sutton SignWriting":               (0x1D800, 0x1DAAF, "",    "Sutton SignWriting"),
    "Glagolitic Supplement":            (0x1E000, 0x1E02F, "_??", "Glagolitic Supplement"),
    "Mende Kikakui":                    (0x1E800, 0x1E8DF, "MEN", "Mende Kikakui"),
    "Adlam":                            (0x1E900, 0x1E95F, "_??", "Adlam"),
    "Arabic Mathematical Alphabetic Symbols":
                                        (0x1EE00, 0x1EEFF, "_MA", "Arabic Mathematical Alphabetic Symbols"),
    "Mahjong Tiles":                    (0x1F000, 0x1F02F, "_GA", "Mahjong Tiles"),
    "Domino Tiles":                     (0x1F030, 0x1F09F, "_GA", "Domino Tiles"),
    "Playing Cards":                    (0x1F0A0, 0x1F0FF, "_GA", "Playing Cards"),
    "Enclosed Alphanumeric Supplement": (0x1F100, 0x1F1FF, "_FO", "Enclosed Alphanumeric Supplement"),
    "Enclosed Ideographic Supplement":  (0x1F200, 0x1F2FF, "_FO", "Enclosed Ideographic Supplement"),
    #
    "Miscellaneous Symbols and Pictographs":    (0x1F300, 0x1F5FF, "",    "Miscellaneous Symbols and Pictographs"),
    "Emoticons":                                (0x1F600, 0x1F64F, "",    "Emoticons"),
    "Ornamental Dingbats":                      (0x1F650, 0x1F67F, "",    "Ornamental Dingbats"),
    "Transport and Map Symbols":                (0x1F680, 0x1F6FF, "",    "Transport and Map Symbols"),
    "Alchemical Symbols":                       (0x1F700, 0x1F77F, "",    "Alchemical Symbols"),
    "Geometric Shapes Extended":                (0x1F780, 0x1F7FF, "",    "Geometric Shapes Extended"),
    "Supplemental Arrows-C":                    (0x1F800, 0x1F8FF, "",    "Supplemental Arrows-C"),
    "Supplemental Symbols and Pictographs":     (0x1F900, 0x1F9FF, "",    "Supplemental Symbols and Pictographs"),
    "CJK Unified Ideographs Extension B":       (0x20000, 0x2A6DF, "_ID", "CJK Unified Ideographs Extension B"),
    "CJK Unified Ideographs Extension C":       (0x2A700, 0x2B73F, "_ID", "CJK Unified Ideographs Extension C"),
    "CJK Unified Ideographs Extension D":       (0x2B740, 0x2B81F, "_ID", "CJK Unified Ideographs Extension D"),
    "CJK Unified Ideographs Extension E":       (0x2B820, 0x2CEAF, "_ID", "CJK Unified Ideographs Extension E"),
    "CJK Unified Ideographs Extension F":       (0x2CEB0, 0x2EBEF, "_ID", "CJK Unified Ideographs Extension F"),
    "CJK Compatibility Ideographs Supplement":  (0x2F800, 0x2FA1F, "_ID", "CJK Compatibility Ideographs Supplement"),
    "Tags":                                     (0xE0000, 0xE007F, "",    "Tags"),
    "Variation Selectors Supplement":           (0xE0100, 0xE01EF, "",    "Variation Selectors Supplement"),
    "Supplementary Private Use Area-A":         (0xF0000, 0xFFFFF, "",    "Supplementary Private Use Area-A"),
    "Supplementary Private Use Area-B":         (0x100000, 0x10FFFF, "",  "Supplementary Private Use Area-B"),
}
