combiningLatin = {
    0x00363: 'COMBINING LATIN SMALL LETTER A',
    0x01de8: 'COMBINING LATIN SMALL LETTER B',
    0x00368: 'COMBINING LATIN SMALL LETTER C',
    0x00369: 'COMBINING LATIN SMALL LETTER D',
    0x00364: 'COMBINING LATIN SMALL LETTER E',
    0x01deb: 'COMBINING LATIN SMALL LETTER F',
    0x01dda: 'COMBINING LATIN SMALL LETTER G',
    0x0036a: 'COMBINING LATIN SMALL LETTER H',
    0x00365: 'COMBINING LATIN SMALL LETTER I',
    # J ???
    0x01ddc: 'COMBINING LATIN SMALL LETTER K',
    0x01ddd: 'COMBINING LATIN SMALL LETTER L',
    0x0036b: 'COMBINING LATIN SMALL LETTER M',
    0x01de0: 'COMBINING LATIN SMALL LETTER N',
    0x00366: 'COMBINING LATIN SMALL LETTER O',
    0x01dee: 'COMBINING LATIN SMALL LETTER P',
    # Q ???
    0x0036c: 'COMBINING LATIN SMALL LETTER R',
    0x01de4: 'COMBINING LATIN SMALL LETTER S',
    0x0036d: 'COMBINING LATIN SMALL LETTER T',
    0x00367: 'COMBINING LATIN SMALL LETTER U',
    0x0036e: 'COMBINING LATIN SMALL LETTER V',
    0x01df1: 'COMBINING LATIN SMALL LETTER W',
    0x0036f: 'COMBINING LATIN SMALL LETTER X',
    # Y ???
    0x01de6: 'COMBINING LATIN SMALL LETTER Z',

    # Why do Devanagri and Grantha get combining digits?

    0x01dd3: 'COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE',
    0x01dd4: 'COMBINING LATIN SMALL LETTER AE',
    0x01dd5: 'COMBINING LATIN SMALL LETTER AO',
    0x01dd6: 'COMBINING LATIN SMALL LETTER AV',
    0x01dd8: 'COMBINING LATIN SMALL LETTER INSULAR D',
    0x01dd9: 'COMBINING LATIN SMALL LETTER ETH',
    0x01de3: 'COMBINING LATIN SMALL LETTER R ROTUNDA',
    0x01de5: 'COMBINING LATIN SMALL LETTER LONG S',
    0x01def: 'COMBINING LATIN SMALL LETTER ESH',
    0x01dea: 'COMBINING LATIN SMALL LETTER SCHWA',

    # Uh, why are alpha and beta "Latin"?
    0x01de7: 'COMBINING LATIN SMALL LETTER ALPHA',
    0x01de9: 'COMBINING LATIN SMALL LETTER BETA',

    # With their own diacritics
    0x01dd7: 'COMBINING LATIN SMALL LETTER C CEDILLA',
    0x01dec: 'COMBINING LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE',
    0x01ded: 'COMBINING LATIN SMALL LETTER O WITH LIGHT CENTRALIZATION STROKE',
    0x01df0: 'COMBINING LATIN SMALL LETTER U WITH LIGHT CENTRALIZATION STROKE',
    0x01df2: 'COMBINING LATIN SMALL LETTER A WITH DIAERESIS',
    0x01df3: 'COMBINING LATIN SMALL LETTER O WITH DIAERESIS',
    0x01df4: 'COMBINING LATIN SMALL LETTER U WITH DIAERESIS',

    # Small capitals
    0x01ddb: 'COMBINING LATIN LETTER SMALL CAPITAL G',
    0x01dde: 'COMBINING LATIN LETTER SMALL CAPITAL L',
    0x01ddf: 'COMBINING LATIN LETTER SMALL CAPITAL M',
    0x01de1: 'COMBINING LATIN LETTER SMALL CAPITAL N',
    0x01de2: 'COMBINING LATIN LETTER SMALL CAPITAL R',

    # Below
    0x01dca: 'COMBINING LATIN SMALL LETTER R BELOW',
}
